// RADIANT v4.18.0 - xAI (Grok) Provider Configuration

export const XAI_PROVIDER_CONFIG = {
  id: 'xai',
  displayName: 'xAI (Grok)',
  apiBase: 'https://api.x.ai/v1',
  authType: 'api_key' as const,
  authHeader: 'Authorization',
  authPrefix: 'Bearer ',
  isEnabled: true,
  
  models: [
    {
      id: 'grok-3',
      displayName: 'Grok 3',
      contextWindow: 131072,
      maxOutputTokens: 8192,
      supportedModalities: ['text'],
      pricing: { inputPer1M: 3.00, outputPer1M: 15.00 },
      capabilities: ['chat', 'reasoning', 'analysis', 'realtime_info'],
      isNovel: false,
      category: 'flagship',
    },
    {
      id: 'grok-3-fast',
      displayName: 'Grok 3 Fast',
      contextWindow: 131072,
      maxOutputTokens: 8192,
      supportedModalities: ['text'],
      pricing: { inputPer1M: 1.00, outputPer1M: 5.00 },
      capabilities: ['chat', 'fast_response'],
      isNovel: false,
      category: 'balanced',
    },
    {
      id: 'grok-3-mini',
      displayName: 'Grok 3 Mini',
      contextWindow: 131072,
      maxOutputTokens: 4096,
      supportedModalities: ['text'],
      pricing: { inputPer1M: 0.30, outputPer1M: 1.50 },
      capabilities: ['chat', 'cost_effective'],
      isNovel: false,
      category: 'economy',
    },
    {
      id: 'grok-2',
      displayName: 'Grok 2',
      contextWindow: 131072,
      maxOutputTokens: 8192,
      supportedModalities: ['text'],
      pricing: { inputPer1M: 2.00, outputPer1M: 10.00 },
      capabilities: ['chat', 'reasoning'],
      isNovel: false,
      category: 'standard',
    },
    {
      id: 'grok-2-vision',
      displayName: 'Grok 2 Vision',
      contextWindow: 32768,
      maxOutputTokens: 4096,
      supportedModalities: ['text', 'image'],
      pricing: { inputPer1M: 2.00, outputPer1M: 10.00 },
      capabilities: ['chat', 'vision', 'image_analysis'],
      isNovel: true,
      category: 'novel',
    },
    {
      id: 'grok-2-mini',
      displayName: 'Grok 2 Mini',
      contextWindow: 131072,
      maxOutputTokens: 4096,
      supportedModalities: ['text'],
      pricing: { inputPer1M: 0.20, outputPer1M: 1.00 },
      capabilities: ['chat'],
      isNovel: false,
      category: 'economy',
    },
    {
      id: 'grok-coder',
      displayName: 'Grok Coder',
      contextWindow: 131072,
      maxOutputTokens: 8192,
      supportedModalities: ['text'],
      pricing: { inputPer1M: 1.50, outputPer1M: 7.50 },
      capabilities: ['chat', 'code_generation', 'code_review'],
      isNovel: true,
      category: 'specialized',
    },
    {
      id: 'grok-analyst',
      displayName: 'Grok Analyst',
      contextWindow: 131072,
      maxOutputTokens: 8192,
      supportedModalities: ['text'],
      pricing: { inputPer1M: 2.00, outputPer1M: 10.00 },
      capabilities: ['chat', 'data_analysis', 'insights'],
      isNovel: true,
      category: 'specialized',
    },
    {
      id: 'grok-embed',
      displayName: 'Grok Embed',
      contextWindow: 8192,
      maxOutputTokens: 0,
      supportedModalities: ['text'],
      pricing: { inputPer1M: 0.10, outputPer1M: 0 },
      capabilities: ['embeddings'],
      isNovel: false,
      category: 'specialized',
    },
    {
      id: 'grok-realtime',
      displayName: 'Grok Realtime',
      contextWindow: 32768,
      maxOutputTokens: 4096,
      supportedModalities: ['text', 'audio'],
      pricing: { inputPer1M: 5.00, outputPer1M: 20.00 },
      capabilities: ['chat', 'voice', 'streaming', 'realtime'],
      isNovel: true,
      category: 'novel',
    },
  ],
} as const;

export type XAIModelId = typeof XAI_PROVIDER_CONFIG.models[number]['id'];
