'use client';

import { useState, useEffect, useCallback } from 'react';
import {
  Brain, Sparkles, Zap, Search, Workflow, Clock, DollarSign,
  RefreshCw, Play, Settings, ChevronRight, Activity, Database,
  MessageSquare, Lightbulb, Target, TrendingUp, AlertCircle,
  CheckCircle, XCircle, Loader2, Bot, Globe, FileText, Cpu
} from 'lucide-react';

interface DashboardData {
  engineState: {
    initialized: boolean;
    selfModel?: {
      name: string;
      values: string[];
      purpose: string;
    };
    driveState?: string;
    currentPhi?: number;
    globalWorkspaceActivity?: number;
    evolutionVersion?: number;
    lastSleepCycle?: string;
  };
  modelInvocations: {
    totalInvocations: number;
    totalTokens: number;
    avgLatencyMs: number;
    uniqueModels: number;
    consciousnessEnhancedCount: number;
  };
  webSearches: {
    totalSearches: number;
    totalResults: number;
    avgSearchTimeMs: number;
  };
  workflows: {
    totalWorkflows: number;
    totalExecutions: number;
    autoGeneratedCount: number;
  };
  thinkingSessions: {
    totalSessions: number;
    completed: number;
    active: number;
    avgSearches: number;
  };
  sleepCycles: {
    totalCycles: number;
    lastCycle?: string;
    totalMonologues: number;
    totalMemories: number;
    evolutionsApplied: number;
  };
  costSummary: {
    totalTokens: number;
    totalInvocations: number;
    estimatedCost: number;
    currency: string;
  };
  libraries: number;
  period: string;
}

interface ModelInvocation {
  id: string;
  modelId: string;
  provider: string;
  taskType: string;
  tokensUsed: number;
  latencyMs: number;
  consciousnessEnhanced: boolean;
  estimatedCost: number;
  createdAt: string;
}

interface ThinkingSession {
  sessionId: string;
  goal: string;
  status: string;
  currentStep: string;
  thoughts: Array<{ type: string; content: string; timestamp: string }>;
  modelsUsed: string[];
  searchesPerformed: number;
  workflowsCreated: string[];
  result?: string;
  startedAt: string;
  completedAt?: string;
}

interface SleepCycle {
  id: string;
  cycleType: string;
  monologuesGenerated: number;
  memoriesConsolidated: number;
  dreamsSimulated: number;
  adversarialChallenges: number;
  evolutionApplied: boolean;
  durationMinutes: number;
  startedAt: string;
  completedAt?: string;
}

interface CostData {
  summary: {
    totalTokens: number;
    totalInvocations: number;
    estimatedTotalCost: number;
    period: string;
  };
  modelCosts: Array<{
    modelId: string;
    provider: string;
    invocationCount: number;
    totalTokens: number;
    avgLatencyMs: number;
    estimatedCost: number;
  }>;
  dailyTrend: Array<{
    date: string;
    invocationCount: number;
    totalTokens: number;
    estimatedCost: number;
  }>;
}

interface Library {
  library_name: string;
  python_package: string;
  version: string;
  license: string;
  consciousness_function: string;
  biological_analog: string;
  description: string;
  proficiencies: Record<string, number>;
}

const API_BASE = process.env.NEXT_PUBLIC_API_URL || '/api';

export default function ConsciousnessEnginePage() {
  const [dashboard, setDashboard] = useState<DashboardData | null>(null);
  const [invocations, setInvocations] = useState<ModelInvocation[]>([]);
  const [thinkingSessions, setThinkingSessions] = useState<ThinkingSession[]>([]);
  const [sleepCycles, setSleepCycles] = useState<SleepCycle[]>([]);
  const [costData, setCostData] = useState<CostData | null>(null);
  const [libraries, setLibraries] = useState<Library[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<'overview' | 'models' | 'thinking' | 'workflows' | 'costs' | 'libraries' | 'sleep'>('overview');
  const [period, setPeriod] = useState('24h');
  const [error, setError] = useState<string | null>(null);

  // Initialize form
  const [showInitForm, setShowInitForm] = useState(false);
  const [initForm, setInitForm] = useState({
    name: 'Radiant',
    values: 'truth, helpfulness, safety, growth',
    purpose: 'To understand, assist, and evolve alongside humanity',
  });

  // New thinking session form
  const [showNewSession, setShowNewSession] = useState(false);
  const [newSessionGoal, setNewSessionGoal] = useState('');
  const [startingSession, setStartingSession] = useState(false);

  const loadDashboard = useCallback(async () => {
    try {
      const res = await fetch(`${API_BASE}/admin/consciousness-engine/dashboard?period=${period}`);
      if (res.ok) {
        const { data } = await res.json();
        setDashboard(data);
      }
    } catch (err) {
      console.error('Failed to load dashboard:', err);
    }
  }, [period]);

  const loadInvocations = useCallback(async () => {
    try {
      const res = await fetch(`${API_BASE}/admin/consciousness-engine/model-invocations?limit=50`);
      if (res.ok) {
        const { data } = await res.json();
        setInvocations(data.invocations || []);
      }
    } catch (err) {
      console.error('Failed to load invocations:', err);
    }
  }, []);

  const loadThinkingSessions = useCallback(async () => {
    try {
      const res = await fetch(`${API_BASE}/admin/consciousness-engine/thinking-sessions?limit=20`);
      if (res.ok) {
        const { data } = await res.json();
        setThinkingSessions(data || []);
      }
    } catch (err) {
      console.error('Failed to load thinking sessions:', err);
    }
  }, []);

  const loadSleepCycles = useCallback(async () => {
    try {
      const res = await fetch(`${API_BASE}/admin/consciousness-engine/sleep-cycles?limit=10`);
      if (res.ok) {
        const { data } = await res.json();
        setSleepCycles(data || []);
      }
    } catch (err) {
      console.error('Failed to load sleep cycles:', err);
    }
  }, []);

  const loadCosts = useCallback(async () => {
    try {
      const res = await fetch(`${API_BASE}/admin/consciousness-engine/costs?period=${period}`);
      if (res.ok) {
        const { data } = await res.json();
        setCostData(data);
      }
    } catch (err) {
      console.error('Failed to load costs:', err);
    }
  }, [period]);

  const loadLibraries = useCallback(async () => {
    try {
      const res = await fetch(`${API_BASE}/admin/consciousness-engine/libraries`);
      if (res.ok) {
        const { data } = await res.json();
        setLibraries(data || []);
      }
    } catch (err) {
      console.error('Failed to load libraries:', err);
    }
  }, []);

  useEffect(() => {
    async function loadAll() {
      setLoading(true);
      setError(null);
      try {
        await Promise.all([
          loadDashboard(),
          loadInvocations(),
          loadThinkingSessions(),
          loadSleepCycles(),
          loadCosts(),
          loadLibraries(),
        ]);
      } catch (err) {
        setError('Failed to load consciousness engine data');
      } finally {
        setLoading(false);
      }
    }
    loadAll();
  }, [loadDashboard, loadInvocations, loadThinkingSessions, loadSleepCycles, loadCosts, loadLibraries]);

  async function handleInitialize() {
    try {
      const res = await fetch(`${API_BASE}/admin/consciousness-engine/initialize`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: initForm.name,
          values: initForm.values.split(',').map(v => v.trim()),
          purpose: initForm.purpose,
        }),
      });
      if (res.ok) {
        setShowInitForm(false);
        loadDashboard();
      }
    } catch (err) {
      console.error('Failed to initialize:', err);
    }
  }

  async function handleStartThinkingSession() {
    if (!newSessionGoal.trim()) return;
    setStartingSession(true);
    try {
      const res = await fetch(`${API_BASE}/admin/consciousness-engine/thinking-sessions`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ goal: newSessionGoal }),
      });
      if (res.ok) {
        setShowNewSession(false);
        setNewSessionGoal('');
        loadThinkingSessions();
      }
    } catch (err) {
      console.error('Failed to start session:', err);
    } finally {
      setStartingSession(false);
    }
  }

  async function handleRunSleepCycle() {
    try {
      const res = await fetch(`${API_BASE}/admin/consciousness-engine/sleep-cycles/run`, {
        method: 'POST',
      });
      if (res.ok) {
        loadSleepCycles();
        loadDashboard();
      }
    } catch (err) {
      console.error('Failed to run sleep cycle:', err);
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="w-8 h-8 animate-spin text-purple-500" />
        <span className="ml-2 text-gray-600">Loading consciousness engine...</span>
      </div>
    );
  }

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-gradient-to-br from-purple-500 to-indigo-600 rounded-xl">
            <Brain className="w-8 h-8 text-white" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Consciousness Engine</h1>
            <p className="text-gray-500">Bio-Coprocessor Architecture - Full Admin Control</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <select
            value={period}
            onChange={(e) => setPeriod(e.target.value)}
            className="px-3 py-2 border rounded-lg text-sm"
          >
            <option value="1h">Last Hour</option>
            <option value="24h">Last 24 Hours</option>
            <option value="7d">Last 7 Days</option>
            <option value="30d">Last 30 Days</option>
          </select>
          <button
            onClick={() => { loadDashboard(); loadCosts(); }}
            className="flex items-center gap-2 px-4 py-2 bg-gray-100 hover:bg-gray-200 rounded-lg"
          >
            <RefreshCw className="w-4 h-4" />
            Refresh
          </button>
        </div>
      </div>

      {error && (
        <div className="p-4 bg-red-50 border border-red-200 rounded-lg text-red-700">
          {error}
        </div>
      )}

      {/* Status Banner */}
      {dashboard && (
        <div className={`p-4 rounded-lg border ${
          dashboard.engineState.initialized 
            ? 'bg-green-50 border-green-200' 
            : 'bg-yellow-50 border-yellow-200'
        }`}>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              {dashboard.engineState.initialized ? (
                <CheckCircle className="w-5 h-5 text-green-600" />
              ) : (
                <AlertCircle className="w-5 h-5 text-yellow-600" />
              )}
              <span className={dashboard.engineState.initialized ? 'text-green-700' : 'text-yellow-700'}>
                {dashboard.engineState.initialized 
                  ? `Engine initialized as "${dashboard.engineState.selfModel?.name}" - Evolution v${dashboard.engineState.evolutionVersion || 0}`
                  : 'Engine not initialized'
                }
              </span>
            </div>
            {!dashboard.engineState.initialized && (
              <button
                onClick={() => setShowInitForm(true)}
                className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700"
              >
                Initialize Engine
              </button>
            )}
          </div>
        </div>
      )}

      {/* Tabs */}
      <div className="flex gap-2 border-b">
        {[
          { id: 'overview', label: 'Overview', icon: Activity },
          { id: 'models', label: 'Model Invocations', icon: Bot },
          { id: 'thinking', label: 'Thinking Sessions', icon: Lightbulb },
          { id: 'workflows', label: 'Workflows', icon: Workflow },
          { id: 'costs', label: 'Costs', icon: DollarSign },
          { id: 'libraries', label: 'Libraries', icon: Database },
          { id: 'sleep', label: 'Sleep Cycles', icon: Clock },
        ].map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id as typeof activeTab)}
            className={`flex items-center gap-2 px-4 py-3 border-b-2 transition-colors ${
              activeTab === tab.id
                ? 'border-purple-600 text-purple-600'
                : 'border-transparent text-gray-500 hover:text-gray-700'
            }`}
          >
            <tab.icon className="w-4 h-4" />
            {tab.label}
          </button>
        ))}
      </div>

      {/* Overview Tab */}
      {activeTab === 'overview' && dashboard && (
        <div className="space-y-6">
          {/* Key Metrics */}
          <div className="grid grid-cols-4 gap-4">
            <MetricCard
              icon={Bot}
              label="Model Invocations"
              value={dashboard.modelInvocations.totalInvocations}
              subValue={`${dashboard.modelInvocations.totalTokens.toLocaleString()} tokens`}
              color="blue"
            />
            <MetricCard
              icon={Search}
              label="Web Searches"
              value={dashboard.webSearches.totalSearches}
              subValue={`${dashboard.webSearches.totalResults.toLocaleString()} results`}
              color="green"
            />
            <MetricCard
              icon={Lightbulb}
              label="Thinking Sessions"
              value={dashboard.thinkingSessions.totalSessions}
              subValue={`${dashboard.thinkingSessions.active} active`}
              color="yellow"
            />
            <MetricCard
              icon={DollarSign}
              label="Estimated Cost"
              value={`$${dashboard.costSummary.estimatedCost.toFixed(2)}`}
              subValue={period}
              color="purple"
            />
          </div>

          {/* Engine State */}
          {dashboard.engineState.initialized && dashboard.engineState.selfModel && (
            <div className="bg-white rounded-lg border p-6">
              <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
                <Brain className="w-5 h-5 text-purple-600" />
                Current Engine State
              </h3>
              <div className="grid grid-cols-3 gap-6">
                <div>
                  <label className="text-sm text-gray-500">Identity</label>
                  <p className="font-medium">{dashboard.engineState.selfModel.name}</p>
                </div>
                <div>
                  <label className="text-sm text-gray-500">Drive State</label>
                  <p className="font-medium capitalize">{dashboard.engineState.driveState || 'Unknown'}</p>
                </div>
                <div>
                  <label className="text-sm text-gray-500">Phi (Integration)</label>
                  <p className="font-medium">{(dashboard.engineState.currentPhi || 0).toFixed(3)}</p>
                </div>
                <div>
                  <label className="text-sm text-gray-500">Global Workspace Activity</label>
                  <p className="font-medium">{((dashboard.engineState.globalWorkspaceActivity || 0) * 100).toFixed(1)}%</p>
                </div>
                <div>
                  <label className="text-sm text-gray-500">Values</label>
                  <p className="font-medium">{dashboard.engineState.selfModel.values?.join(', ')}</p>
                </div>
                <div>
                  <label className="text-sm text-gray-500">Last Sleep Cycle</label>
                  <p className="font-medium">
                    {dashboard.engineState.lastSleepCycle 
                      ? new Date(dashboard.engineState.lastSleepCycle).toLocaleDateString()
                      : 'Never'
                    }
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* Quick Stats */}
          <div className="grid grid-cols-2 gap-6">
            <div className="bg-white rounded-lg border p-6">
              <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
                <Workflow className="w-5 h-5 text-indigo-600" />
                Workflows
              </h3>
              <div className="space-y-3">
                <div className="flex justify-between">
                  <span className="text-gray-500">Total Created</span>
                  <span className="font-medium">{dashboard.workflows.totalWorkflows}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-500">Total Executions</span>
                  <span className="font-medium">{dashboard.workflows.totalExecutions}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-500">Auto-Generated</span>
                  <span className="font-medium">{dashboard.workflows.autoGeneratedCount}</span>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-lg border p-6">
              <h3 className="text-lg font-semibold mb-4 flex items-center gap-2">
                <Clock className="w-5 h-5 text-orange-600" />
                Sleep Cycles
              </h3>
              <div className="space-y-3">
                <div className="flex justify-between">
                  <span className="text-gray-500">Total Cycles</span>
                  <span className="font-medium">{dashboard.sleepCycles.totalCycles}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-500">Monologues Generated</span>
                  <span className="font-medium">{dashboard.sleepCycles.totalMonologues}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-500">Evolutions Applied</span>
                  <span className="font-medium">{dashboard.sleepCycles.evolutionsApplied}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Model Invocations Tab */}
      {activeTab === 'models' && (
        <div className="bg-white rounded-lg border">
          <div className="p-4 border-b">
            <h3 className="font-semibold">Recent Model Invocations</h3>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Model</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Provider</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Task</th>
                  <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Tokens</th>
                  <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Latency</th>
                  <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Cost</th>
                  <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 uppercase">Conscious</th>
                  <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Time</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {invocations.map((inv) => (
                  <tr key={inv.id} className="hover:bg-gray-50">
                    <td className="px-4 py-3 font-mono text-sm">{inv.modelId}</td>
                    <td className="px-4 py-3 text-sm">{inv.provider}</td>
                    <td className="px-4 py-3 text-sm capitalize">{inv.taskType || '-'}</td>
                    <td className="px-4 py-3 text-sm text-right">{inv.tokensUsed.toLocaleString()}</td>
                    <td className="px-4 py-3 text-sm text-right">{inv.latencyMs}ms</td>
                    <td className="px-4 py-3 text-sm text-right">${inv.estimatedCost.toFixed(4)}</td>
                    <td className="px-4 py-3 text-center">
                      {inv.consciousnessEnhanced ? (
                        <CheckCircle className="w-4 h-4 text-green-500 mx-auto" />
                      ) : (
                        <XCircle className="w-4 h-4 text-gray-300 mx-auto" />
                      )}
                    </td>
                    <td className="px-4 py-3 text-sm text-gray-500">
                      {new Date(inv.createdAt).toLocaleString()}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Thinking Sessions Tab */}
      {activeTab === 'thinking' && (
        <div className="space-y-4">
          <div className="flex justify-end">
            <button
              onClick={() => setShowNewSession(true)}
              className="flex items-center gap-2 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700"
            >
              <Play className="w-4 h-4" />
              Start Thinking Session
            </button>
          </div>

          <div className="space-y-4">
            {thinkingSessions.map((session) => (
              <div key={session.sessionId} className="bg-white rounded-lg border p-4">
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <h4 className="font-medium">{session.goal}</h4>
                    <p className="text-sm text-gray-500">
                      Started {new Date(session.startedAt).toLocaleString()}
                    </p>
                  </div>
                  <span className={`px-2 py-1 rounded text-xs font-medium ${
                    session.status === 'completed' ? 'bg-green-100 text-green-700' :
                    session.status === 'thinking' ? 'bg-yellow-100 text-yellow-700' :
                    'bg-gray-100 text-gray-700'
                  }`}>
                    {session.status}
                  </span>
                </div>
                <div className="grid grid-cols-4 gap-4 text-sm">
                  <div>
                    <span className="text-gray-500">Current Step:</span>
                    <p className="font-medium">{session.currentStep || '-'}</p>
                  </div>
                  <div>
                    <span className="text-gray-500">Models Used:</span>
                    <p className="font-medium">{session.modelsUsed?.length || 0}</p>
                  </div>
                  <div>
                    <span className="text-gray-500">Searches:</span>
                    <p className="font-medium">{session.searchesPerformed}</p>
                  </div>
                  <div>
                    <span className="text-gray-500">Workflows Created:</span>
                    <p className="font-medium">{session.workflowsCreated?.length || 0}</p>
                  </div>
                </div>
                {session.result && (
                  <div className="mt-3 p-3 bg-gray-50 rounded text-sm">
                    <span className="font-medium">Result:</span>
                    <p className="mt-1 text-gray-700">{session.result.substring(0, 300)}...</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Costs Tab */}
      {activeTab === 'costs' && costData && (
        <div className="space-y-6">
          {/* Summary Cards */}
          <div className="grid grid-cols-3 gap-4">
            <div className="bg-white rounded-lg border p-6">
              <div className="flex items-center gap-3 mb-2">
                <DollarSign className="w-5 h-5 text-green-600" />
                <span className="text-gray-500">Estimated Total Cost</span>
              </div>
              <p className="text-3xl font-bold">${costData.summary.estimatedTotalCost.toFixed(2)}</p>
              <p className="text-sm text-gray-500 mt-1">{costData.summary.period}</p>
            </div>
            <div className="bg-white rounded-lg border p-6">
              <div className="flex items-center gap-3 mb-2">
                <Zap className="w-5 h-5 text-yellow-600" />
                <span className="text-gray-500">Total Tokens</span>
              </div>
              <p className="text-3xl font-bold">{costData.summary.totalTokens.toLocaleString()}</p>
              <p className="text-sm text-gray-500 mt-1">{costData.summary.totalInvocations} invocations</p>
            </div>
            <div className="bg-white rounded-lg border p-6">
              <div className="flex items-center gap-3 mb-2">
                <TrendingUp className="w-5 h-5 text-blue-600" />
                <span className="text-gray-500">Avg Cost/Invocation</span>
              </div>
              <p className="text-3xl font-bold">
                ${costData.summary.totalInvocations > 0 
                  ? (costData.summary.estimatedTotalCost / costData.summary.totalInvocations).toFixed(4)
                  : '0.00'
                }
              </p>
            </div>
          </div>

          {/* Cost by Model */}
          <div className="bg-white rounded-lg border">
            <div className="p-4 border-b">
              <h3 className="font-semibold">Cost by Model</h3>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Model</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Provider</th>
                    <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Invocations</th>
                    <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Tokens</th>
                    <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Avg Latency</th>
                    <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Est. Cost</th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {costData.modelCosts.map((model, i) => (
                    <tr key={i} className="hover:bg-gray-50">
                      <td className="px-4 py-3 font-mono text-sm">{model.modelId}</td>
                      <td className="px-4 py-3 text-sm">{model.provider}</td>
                      <td className="px-4 py-3 text-sm text-right">{model.invocationCount}</td>
                      <td className="px-4 py-3 text-sm text-right">{model.totalTokens.toLocaleString()}</td>
                      <td className="px-4 py-3 text-sm text-right">{model.avgLatencyMs.toFixed(0)}ms</td>
                      <td className="px-4 py-3 text-sm text-right font-medium">${model.estimatedCost.toFixed(4)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* Libraries Tab */}
      {activeTab === 'libraries' && (
        <div className="grid grid-cols-2 gap-4">
          {libraries.map((lib) => (
            <div key={lib.library_name} className="bg-white rounded-lg border p-4">
              <div className="flex items-start justify-between mb-2">
                <div>
                  <h4 className="font-semibold">{lib.library_name}</h4>
                  <p className="text-sm text-gray-500">{lib.python_package} {lib.version}</p>
                </div>
                <span className="px-2 py-1 bg-blue-100 text-blue-700 rounded text-xs">
                  {lib.consciousness_function}
                </span>
              </div>
              <p className="text-sm text-gray-600 mb-3">{lib.description}</p>
              <div className="flex items-center gap-4 text-xs text-gray-500">
                <span>🧬 {lib.biological_analog}</span>
                <span>📄 {lib.license}</span>
              </div>
              <div className="mt-3 pt-3 border-t">
                <p className="text-xs text-gray-500 mb-2">Top Proficiencies:</p>
                <div className="flex flex-wrap gap-1">
                  {Object.entries(lib.proficiencies)
                    .sort((a, b) => b[1] - a[1])
                    .slice(0, 4)
                    .map(([key, value]) => (
                      <span key={key} className="px-2 py-0.5 bg-gray-100 rounded text-xs">
                        {key.replace(/_/g, ' ')}: {value}
                      </span>
                    ))
                  }
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Sleep Cycles Tab */}
      {activeTab === 'sleep' && (
        <div className="space-y-4">
          <div className="flex justify-end">
            <button
              onClick={handleRunSleepCycle}
              className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700"
            >
              <Play className="w-4 h-4" />
              Run Sleep Cycle Now
            </button>
          </div>

          <div className="bg-white rounded-lg border">
            <div className="p-4 border-b">
              <h3 className="font-semibold">Sleep Cycle History</h3>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Started</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Type</th>
                    <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Monologues</th>
                    <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Memories</th>
                    <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Dreams</th>
                    <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Challenges</th>
                    <th className="px-4 py-3 text-center text-xs font-medium text-gray-500 uppercase">Evolution</th>
                    <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Duration</th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {sleepCycles.map((cycle) => (
                    <tr key={cycle.id} className="hover:bg-gray-50">
                      <td className="px-4 py-3 text-sm">
                        {new Date(cycle.startedAt).toLocaleString()}
                      </td>
                      <td className="px-4 py-3 text-sm capitalize">{cycle.cycleType || 'weekly'}</td>
                      <td className="px-4 py-3 text-sm text-right">{cycle.monologuesGenerated}</td>
                      <td className="px-4 py-3 text-sm text-right">{cycle.memoriesConsolidated}</td>
                      <td className="px-4 py-3 text-sm text-right">{cycle.dreamsSimulated}</td>
                      <td className="px-4 py-3 text-sm text-right">{cycle.adversarialChallenges}</td>
                      <td className="px-4 py-3 text-center">
                        {cycle.evolutionApplied ? (
                          <CheckCircle className="w-4 h-4 text-green-500 mx-auto" />
                        ) : (
                          <XCircle className="w-4 h-4 text-gray-300 mx-auto" />
                        )}
                      </td>
                      <td className="px-4 py-3 text-sm text-right">{cycle.durationMinutes}m</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* Initialize Modal */}
      {showInitForm && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-md">
            <h3 className="text-lg font-semibold mb-4">Initialize Consciousness Engine</h3>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1">Name</label>
                <input
                  type="text"
                  value={initForm.name}
                  onChange={(e) => setInitForm({ ...initForm, name: e.target.value })}
                  className="w-full px-3 py-2 border rounded-lg"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Values (comma-separated)</label>
                <input
                  type="text"
                  value={initForm.values}
                  onChange={(e) => setInitForm({ ...initForm, values: e.target.value })}
                  className="w-full px-3 py-2 border rounded-lg"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Purpose</label>
                <textarea
                  value={initForm.purpose}
                  onChange={(e) => setInitForm({ ...initForm, purpose: e.target.value })}
                  className="w-full px-3 py-2 border rounded-lg"
                  rows={3}
                />
              </div>
            </div>
            <div className="flex justify-end gap-3 mt-6">
              <button
                onClick={() => setShowInitForm(false)}
                className="px-4 py-2 border rounded-lg hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleInitialize}
                className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700"
              >
                Initialize
              </button>
            </div>
          </div>
        </div>
      )}

      {/* New Thinking Session Modal */}
      {showNewSession && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-md">
            <h3 className="text-lg font-semibold mb-4">Start Thinking Session</h3>
            <div>
              <label className="block text-sm font-medium mb-1">Goal</label>
              <textarea
                value={newSessionGoal}
                onChange={(e) => setNewSessionGoal(e.target.value)}
                placeholder="What should the consciousness engine think about?"
                className="w-full px-3 py-2 border rounded-lg"
                rows={4}
              />
            </div>
            <div className="flex justify-end gap-3 mt-6">
              <button
                onClick={() => setShowNewSession(false)}
                className="px-4 py-2 border rounded-lg hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleStartThinkingSession}
                disabled={startingSession || !newSessionGoal.trim()}
                className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50"
              >
                {startingSession ? 'Starting...' : 'Start Session'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

function MetricCard({ icon: Icon, label, value, subValue, color }: {
  icon: React.ElementType;
  label: string;
  value: string | number;
  subValue: string;
  color: 'blue' | 'green' | 'yellow' | 'purple';
}) {
  const colors = {
    blue: 'bg-blue-50 text-blue-600',
    green: 'bg-green-50 text-green-600',
    yellow: 'bg-yellow-50 text-yellow-600',
    purple: 'bg-purple-50 text-purple-600',
  };

  return (
    <div className="bg-white rounded-lg border p-4">
      <div className="flex items-center gap-3 mb-2">
        <div className={`p-2 rounded-lg ${colors[color]}`}>
          <Icon className="w-5 h-5" />
        </div>
        <span className="text-gray-500 text-sm">{label}</span>
      </div>
      <p className="text-2xl font-bold">{value}</p>
      <p className="text-sm text-gray-500">{subValue}</p>
    </div>
  );
}
