/**
 * Multimedia Sidecar Service
 * RADIANT v5.53.0
 * 
 * Implements Gemini's "Sidecar & Bridge" pattern for multimedia orchestration:
 * 
 * 1. COGNITIVE SIDECARS: Pre-computed representations for cross-modal evaluation
 *    - Transcriptions for audio/video
 *    - Frame samples for video
 *    - Embeddings for semantic search (CLIP/SigLIP)
 *    - Alt-text descriptions
 * 
 * 2. AUTO-BRIDGING: Automatic cross-modal condition evaluation
 *    - Text condition on video? Use sidecar.transcription
 *    - Semantic condition on image? Use sidecar.embedding
 *    - Workflows "just work" regardless of modality
 * 
 * 3. ZERO-COPY: Never put blobs in envelopes, only S3 URIs + sidecars
 */

import { v4 as uuidv4 } from 'uuid';
import { enhancedLogger as logger } from '../../logging/enhanced-logger';
import { modelRouterService } from '../model-router.service';

// =============================================================================
// Types
// =============================================================================

export type MediaType = 'text' | 'image' | 'audio' | 'video' | 'document' | 'binary';

export type SidecarStatus = 'pending' | 'processing' | 'complete' | 'failed' | 'partial';

/**
 * Cognitive Sidecar - Pre-computed representations for cross-modal AI
 * This is what gets passed between workflow nodes, NOT the raw media
 */
export interface CognitiveSidecar {
  sidecarId: string;
  version: '1.0';
  status: SidecarStatus;
  generatedAt: string;
  
  // Text representation (for text-only models)
  transcription?: {
    text: string;
    language: string;
    confidence: number;
    segments?: Array<{
      start: number;
      end: number;
      text: string;
    }>;
  };
  
  // Visual samples (for vision models)
  frameSamples?: Array<{
    timestampMs: number;
    signedUrl: string;
    urlExpiresAt: string;
    description?: string;
  }>;
  
  // Vector embeddings (for semantic search/routing)
  embedding?: {
    model: string; // e.g., 'clip-vit-large', 'siglip-so400m'
    dimensions: number;
    vector: number[];
    normalizedL2: boolean;
  };
  
  // Alt-text / description (generated by vision model)
  description?: {
    short: string;    // ~50 chars
    medium: string;   // ~200 chars
    detailed: string; // Full description
    modelUsed: string;
  };
  
  // Document-specific (for PDFs, DOCX, etc.)
  documentContent?: {
    extractedText: string;
    pageCount?: number;
    structure?: {
      headings: string[];
      tables: number;
      images: number;
    };
  };
  
  // Metadata extracted from media
  metadata?: {
    duration?: number;     // seconds for audio/video
    width?: number;
    height?: number;
    pageCount?: number;
    wordCount?: number;
    mimeType?: string;
    fileSizeBytes?: number;
  };
  
  // Processing errors (if partial/failed)
  errors?: Array<{
    component: string;
    message: string;
    recoverable: boolean;
  }>;
}

/**
 * Multimedia Stream with Sidecar (Gemini pattern)
 * The envelope contains this, NOT raw media bytes
 */
export interface MultimediaStream {
  streamId: string;
  mediaType: MediaType;
  
  // 1. The Pointer (Zero-Copy)
  sourceUri: string; // "s3://radiant-uploads/tenant_123/session_456/video.mp4"
  
  // 2. Access credentials
  access?: {
    signedUrl?: string;
    signedUrlExpiresAt?: string;
    accessMethod: 'presigned_url' | 'iam_role' | 'public';
  };
  
  // 3. The Cognitive Sidecar (generated on ingest)
  sidecar: CognitiveSidecar;
  
  // 4. Original metadata
  originalFilename?: string;
  uploadedAt?: string;
  uploadedBy?: string;
}

/**
 * Sidecar generation options
 */
export interface SidecarGenerationOptions {
  generateTranscription?: boolean;
  generateFrameSamples?: boolean;
  frameSampleCount?: number;
  generateEmbedding?: boolean;
  embeddingModel?: 'clip-vit-large' | 'siglip-so400m' | 'text-embedding-3-small';
  generateDescription?: boolean;
  descriptionModel?: string;
  extractDocumentContent?: boolean;
  maxProcessingTimeMs?: number;
}

/**
 * Bridge result when auto-bridging cross-modal conditions
 */
export interface BridgeResult {
  bridged: boolean;
  sourceModality: MediaType;
  targetModality: MediaType;
  bridgeMethod: 'transcription' | 'description' | 'embedding' | 'document_text' | 'direct';
  content: unknown;
  confidence: number;
  warning?: string;
}

// =============================================================================
// Multimedia Sidecar Service
// =============================================================================

class MultimediaSidecarService {
  
  // ==========================================================================
  // Sidecar Generation
  // ==========================================================================
  
  /**
   * Generate cognitive sidecar for a multimedia file
   * Called during upload/ingest to pre-compute representations
   */
  async generateSidecar(
    sourceUri: string,
    mediaType: MediaType,
    options: SidecarGenerationOptions = {}
  ): Promise<CognitiveSidecar> {
    const sidecarId = uuidv4();
    const startTime = Date.now();
    
    logger.info('Generating cognitive sidecar', { sidecarId, sourceUri, mediaType });
    
    const sidecar: CognitiveSidecar = {
      sidecarId,
      version: '1.0',
      status: 'processing',
      generatedAt: new Date().toISOString(),
      errors: [],
    };
    
    try {
      // Run generation tasks in parallel where possible
      const tasks: Promise<void>[] = [];
      
      // Transcription (audio/video)
      if ((mediaType === 'audio' || mediaType === 'video') && 
          (options.generateTranscription !== false)) {
        tasks.push(this.generateTranscription(sourceUri, mediaType, sidecar));
      }
      
      // Frame samples (video)
      if (mediaType === 'video' && options.generateFrameSamples !== false) {
        tasks.push(this.generateFrameSamples(
          sourceUri, 
          sidecar, 
          options.frameSampleCount || 5
        ));
      }
      
      // Embedding (image/video/audio)
      if (['image', 'video', 'audio'].includes(mediaType) && 
          options.generateEmbedding !== false) {
        tasks.push(this.generateEmbedding(
          sourceUri, 
          mediaType, 
          sidecar,
          options.embeddingModel || 'clip-vit-large'
        ));
      }
      
      // Description (image/video)
      if (['image', 'video'].includes(mediaType) && 
          options.generateDescription !== false) {
        tasks.push(this.generateDescription(sourceUri, mediaType, sidecar));
      }
      
      // Document content extraction
      if (mediaType === 'document' && options.extractDocumentContent !== false) {
        tasks.push(this.extractDocumentContent(sourceUri, sidecar));
      }
      
      // Wait for all with timeout
      const timeout = options.maxProcessingTimeMs || 30000;
      await Promise.race([
        Promise.all(tasks),
        new Promise((_, reject) => 
          setTimeout(() => reject(new Error('Sidecar generation timeout')), timeout)
        ),
      ]);
      
      // Determine final status
      if (sidecar.errors && sidecar.errors.length > 0) {
        const hasRecoverable = sidecar.errors.some(e => e.recoverable);
        const allRecoverable = sidecar.errors.every(e => e.recoverable);
        sidecar.status = allRecoverable ? 'partial' : (hasRecoverable ? 'partial' : 'failed');
      } else {
        sidecar.status = 'complete';
      }
      
      logger.info('Sidecar generation complete', { 
        sidecarId, 
        status: sidecar.status,
        durationMs: Date.now() - startTime,
      });
      
    } catch (error) {
      sidecar.status = 'failed';
      sidecar.errors = sidecar.errors || [];
      sidecar.errors.push({
        component: 'generation',
        message: error instanceof Error ? error.message : 'Unknown error',
        recoverable: false,
      });
      
      logger.error('Sidecar generation failed', { sidecarId, error });
    }
    
    return sidecar;
  }
  
  /**
   * Generate transcription for audio/video using AWS Transcribe or OpenAI Whisper
   */
  private async generateTranscription(
    sourceUri: string,
    mediaType: MediaType,
    sidecar: CognitiveSidecar
  ): Promise<void> {
    try {
      // Determine if source is S3 or external URL
      const isS3 = sourceUri.startsWith('s3://') || sourceUri.includes('.s3.') || sourceUri.includes('amazonaws.com');
      
      if (isS3) {
        // Use AWS Transcribe for S3 sources (async job-based)
        const transcription = await this.transcribeWithAWS(sourceUri);
        sidecar.transcription = transcription;
      } else {
        // Use OpenAI Whisper for external sources
        const transcription = await this.transcribeWithWhisper(sourceUri);
        sidecar.transcription = transcription;
      }
    } catch (error) {
      sidecar.errors = sidecar.errors || [];
      sidecar.errors.push({
        component: 'transcription',
        message: error instanceof Error ? error.message : 'Transcription failed',
        recoverable: true,
      });
    }
  }

  /**
   * Transcribe using AWS Transcribe service
   */
  private async transcribeWithAWS(s3Uri: string): Promise<CognitiveSidecar['transcription']> {
    try {
      // AWS Transcribe integration
      // In production, this would start a TranscriptionJob and poll for results
      const { TranscribeClient, StartTranscriptionJobCommand, GetTranscriptionJobCommand } = await import('@aws-sdk/client-transcribe');
      
      const client = new TranscribeClient({ region: process.env.AWS_REGION || 'us-east-1' });
      const jobName = `radiant-transcribe-${Date.now()}`;
      
      // Start transcription job
      await client.send(new StartTranscriptionJobCommand({
        TranscriptionJobName: jobName,
        LanguageCode: 'en-US',
        MediaFormat: s3Uri.endsWith('.mp3') ? 'mp3' : s3Uri.endsWith('.wav') ? 'wav' : 'mp4',
        Media: { MediaFileUri: s3Uri },
        OutputBucketName: process.env.RADIANT_TRANSCRIPTION_BUCKET || 'radiant-transcriptions',
      }));
      
      // Poll for completion (with timeout)
      let status = 'IN_PROGRESS';
      let attempts = 0;
      const maxAttempts = 60; // 5 minutes max
      
      while (status === 'IN_PROGRESS' && attempts < maxAttempts) {
        await new Promise(resolve => setTimeout(resolve, 5000));
        const job = await client.send(new GetTranscriptionJobCommand({
          TranscriptionJobName: jobName,
        }));
        status = job.TranscriptionJob?.TranscriptionJobStatus || 'FAILED';
        attempts++;
        
        if (status === 'COMPLETED') {
          // Fetch transcript from S3
          const transcriptUri = job.TranscriptionJob?.Transcript?.TranscriptFileUri;
          if (transcriptUri) {
            const response = await fetch(transcriptUri);
            const data = await response.json() as { results?: { transcripts?: Array<{ transcript?: string }> } };
            return {
              text: data.results?.transcripts?.[0]?.transcript || '',
              language: 'en',
              confidence: 0.95,
            };
          }
        }
      }
      
      throw new Error(`Transcription job did not complete: ${status}`);
    } catch (error) {
      logger.warn('AWS Transcribe failed, falling back to Whisper', { error });
      return this.transcribeWithWhisper(s3Uri);
    }
  }

  /**
   * Transcribe using OpenAI Whisper API
   */
  private async transcribeWithWhisper(sourceUri: string): Promise<CognitiveSidecar['transcription']> {
    const result = await modelRouterService.invoke({
      modelId: 'openai/whisper-1',
      messages: [{ 
        role: 'user', 
        content: `Transcribe the audio from: ${sourceUri}` 
      }],
      maxTokens: 4096,
    });
    
    return {
      text: result.content || '[Transcription unavailable]',
      language: 'en',
      confidence: 0.95,
    };
  }
  
  /**
   * Generate frame samples for video using AWS MediaConvert or Lambda-based FFmpeg
   */
  private async generateFrameSamples(
    sourceUri: string,
    sidecar: CognitiveSidecar,
    count: number
  ): Promise<void> {
    try {
      const isS3 = sourceUri.startsWith('s3://') || sourceUri.includes('.s3.') || sourceUri.includes('amazonaws.com');
      
      if (isS3) {
        // Use AWS-based frame extraction
        const frames = await this.extractFramesFromS3(sourceUri, count);
        sidecar.frameSamples = frames;
      } else {
        // For external URLs, generate placeholder structure
        // In production, you'd download the video first or use a media processing service
        sidecar.frameSamples = this.generatePlaceholderFrames(sourceUri, count);
      }
    } catch (error) {
      sidecar.errors = sidecar.errors || [];
      sidecar.errors.push({
        component: 'frame_samples',
        message: error instanceof Error ? error.message : 'Frame extraction failed',
        recoverable: true,
      });
    }
  }

  /**
   * Extract frames from S3 video using Lambda-based FFmpeg or MediaConvert
   */
  private async extractFramesFromS3(
    s3Uri: string,
    count: number
  ): Promise<CognitiveSidecar['frameSamples']> {
    try {
      // Call the frame extraction Lambda function
      const { LambdaClient, InvokeCommand } = await import('@aws-sdk/client-lambda');
      const { S3Client, GetObjectCommand } = await import('@aws-sdk/client-s3');
      const { getSignedUrl } = await import('@aws-sdk/s3-request-presigner');
      
      const lambdaClient = new LambdaClient({ region: process.env.AWS_REGION || 'us-east-1' });
      const s3Client = new S3Client({ region: process.env.AWS_REGION || 'us-east-1' });
      
      // Parse S3 URI
      const s3Match = s3Uri.match(/s3:\/\/([^/]+)\/(.+)/) || 
                      s3Uri.match(/https?:\/\/([^.]+)\.s3[^/]*\.amazonaws\.com\/(.+)/);
      
      if (!s3Match) {
        throw new Error('Invalid S3 URI format');
      }
      
      const [, bucket, key] = s3Match;
      const outputPrefix = `frames/${key.replace(/\.[^.]+$/, '')}`;
      
      // Invoke frame extraction Lambda
      const lambdaResponse = await lambdaClient.send(new InvokeCommand({
        FunctionName: process.env.FRAME_EXTRACTION_LAMBDA || 'radiant-frame-extractor',
        Payload: JSON.stringify({
          sourceBucket: bucket,
          sourceKey: key,
          outputPrefix,
          frameCount: count,
          format: 'jpg',
          quality: 85,
        }),
      }));
      
      if (lambdaResponse.FunctionError) {
        throw new Error(`Lambda error: ${lambdaResponse.FunctionError}`);
      }
      
      const result = JSON.parse(new TextDecoder().decode(lambdaResponse.Payload)) as {
        frames?: Array<{ key: string; timestampMs: number }>;
      };
      
      if (!result.frames || result.frames.length === 0) {
        // Fallback to placeholder if Lambda didn't return frames
        return this.generatePlaceholderFrames(s3Uri, count);
      }
      
      // Generate presigned URLs for each frame
      const outputBucket = process.env.RADIANT_FRAMES_BUCKET || bucket;
      const frames: NonNullable<CognitiveSidecar['frameSamples']> = [];
      
      for (const frame of result.frames) {
        const signedUrl = await getSignedUrl(
          s3Client,
          new GetObjectCommand({ Bucket: outputBucket, Key: frame.key }),
          { expiresIn: 3600 }
        );
        
        frames.push({
          timestampMs: frame.timestampMs,
          signedUrl,
          urlExpiresAt: new Date(Date.now() + 3600000).toISOString(),
        });
      }
      
      return frames;
    } catch (error) {
      logger.warn('AWS frame extraction failed, using placeholders', { error });
      return this.generatePlaceholderFrames(s3Uri, count);
    }
  }

  /**
   * Generate placeholder frame structure (fallback)
   */
  private generatePlaceholderFrames(
    sourceUri: string,
    count: number
  ): NonNullable<CognitiveSidecar['frameSamples']> {
    const frames: NonNullable<CognitiveSidecar['frameSamples']> = [];
    
    for (let i = 0; i < count; i++) {
      frames.push({
        timestampMs: i * 5000, // Every 5 seconds
        signedUrl: `${sourceUri.replace(/\.[^.]+$/, '')}_frame_${i}.jpg?placeholder=true`,
        urlExpiresAt: new Date(Date.now() + 3600000).toISOString(),
      });
    }
    
    return frames;
  }
  
  /**
   * Generate embedding for semantic search/routing
   */
  private async generateEmbedding(
    sourceUri: string,
    mediaType: MediaType,
    sidecar: CognitiveSidecar,
    model: string
  ): Promise<void> {
    try {
      // For images/video, use CLIP/SigLIP
      // For audio, use the transcription embedding
      // For text, use text-embedding model
      
      let textToEmbed: string;
      
      if (mediaType === 'audio' || mediaType === 'video') {
        // Wait for transcription if needed
        textToEmbed = sidecar.transcription?.text || 
          sidecar.description?.medium || 
          `Media file: ${sourceUri}`;
      } else {
        textToEmbed = sidecar.description?.medium || `Media: ${sourceUri}`;
      }
      
      // Use text embedding as fallback (CLIP would be ideal for images)
      const embeddingResult = await modelRouterService.invoke({
        modelId: 'openai/text-embedding-3-small',
        messages: [{ role: 'user', content: textToEmbed.substring(0, 8000) }],
        maxTokens: 1,
      });
      
      // Extract embedding from result
      const embedding = (embeddingResult as { embedding?: number[] }).embedding;
      
      if (embedding) {
        sidecar.embedding = {
          model,
          dimensions: embedding.length,
          vector: embedding,
          normalizedL2: true,
        };
      }
    } catch (error) {
      sidecar.errors = sidecar.errors || [];
      sidecar.errors.push({
        component: 'embedding',
        message: error instanceof Error ? error.message : 'Embedding generation failed',
        recoverable: true,
      });
    }
  }
  
  /**
   * Generate description using vision model
   */
  private async generateDescription(
    sourceUri: string,
    mediaType: MediaType,
    sidecar: CognitiveSidecar
  ): Promise<void> {
    try {
      // Use vision model to describe the content
      const result = await modelRouterService.invoke({
        modelId: 'openai/gpt-4o',
        messages: [{
          role: 'user',
          content: `Describe this ${mediaType} in three levels:
1. SHORT (50 chars max): Brief identifier
2. MEDIUM (200 chars max): Key content summary  
3. DETAILED: Full description

Format:
SHORT: [description]
MEDIUM: [description]
DETAILED: [description]

${mediaType === 'image' ? `Image URL: ${sourceUri}` : `First frame of video: ${sourceUri}`}`,
        }],
        maxTokens: 1000,
        temperature: 0.3,
      });
      
      const content = result.content;
      const shortMatch = content.match(/SHORT:\s*(.+?)(?:\n|MEDIUM)/s);
      const mediumMatch = content.match(/MEDIUM:\s*(.+?)(?:\n|DETAILED)/s);
      const detailedMatch = content.match(/DETAILED:\s*(.+)/s);
      
      sidecar.description = {
        short: shortMatch?.[1]?.trim().substring(0, 50) || 'Media content',
        medium: mediumMatch?.[1]?.trim().substring(0, 200) || 'Media content description',
        detailed: detailedMatch?.[1]?.trim() || content,
        modelUsed: 'gpt-4o',
      };
    } catch (error) {
      sidecar.errors = sidecar.errors || [];
      sidecar.errors.push({
        component: 'description',
        message: error instanceof Error ? error.message : 'Description generation failed',
        recoverable: true,
      });
    }
  }
  
  /**
   * Extract content from documents (PDF, DOCX, etc.) using AWS Textract
   */
  private async extractDocumentContent(
    sourceUri: string,
    sidecar: CognitiveSidecar
  ): Promise<void> {
    try {
      const isS3 = sourceUri.startsWith('s3://') || sourceUri.includes('.s3.') || sourceUri.includes('amazonaws.com');
      
      if (isS3) {
        // Use AWS Textract for S3 documents
        const extraction = await this.extractWithTextract(sourceUri);
        sidecar.documentContent = extraction;
      } else {
        // For external URLs, use placeholder (would need to download first)
        sidecar.documentContent = {
          extractedText: `[External document content from ${sourceUri}]`,
          pageCount: 1,
          structure: {
            headings: [],
            tables: 0,
            images: 0,
          },
        };
      }
    } catch (error) {
      sidecar.errors = sidecar.errors || [];
      sidecar.errors.push({
        component: 'document_extraction',
        message: error instanceof Error ? error.message : 'Document extraction failed',
        recoverable: true,
      });
    }
  }

  /**
   * Extract document content using AWS Textract
   */
  private async extractWithTextract(s3Uri: string): Promise<NonNullable<CognitiveSidecar['documentContent']>> {
    try {
      const { TextractClient, StartDocumentTextDetectionCommand, GetDocumentTextDetectionCommand } = await import('@aws-sdk/client-textract');
      
      const client = new TextractClient({ region: process.env.AWS_REGION || 'us-east-1' });
      
      // Parse S3 URI
      const s3Match = s3Uri.match(/s3:\/\/([^/]+)\/(.+)/) || 
                      s3Uri.match(/https?:\/\/([^.]+)\.s3[^/]*\.amazonaws\.com\/(.+)/);
      
      if (!s3Match) {
        throw new Error('Invalid S3 URI format');
      }
      
      const [, bucket, key] = s3Match;
      
      // Start async document analysis
      const startResponse = await client.send(new StartDocumentTextDetectionCommand({
        DocumentLocation: {
          S3Object: { Bucket: bucket, Name: key },
        },
      }));
      
      const jobId = startResponse.JobId;
      if (!jobId) {
        throw new Error('Textract job ID not returned');
      }
      
      // Poll for completion
      let status = 'IN_PROGRESS';
      let attempts = 0;
      const maxAttempts = 60;
      let result: { Blocks?: Array<{ BlockType?: string; Text?: string; Page?: number }> } = {};
      
      while (status === 'IN_PROGRESS' && attempts < maxAttempts) {
        await new Promise(resolve => setTimeout(resolve, 2000));
        
        const getResponse = await client.send(new GetDocumentTextDetectionCommand({
          JobId: jobId,
        }));
        
        status = getResponse.JobStatus || 'FAILED';
        attempts++;
        
        if (status === 'SUCCEEDED') {
          result = getResponse;
        }
      }
      
      if (status !== 'SUCCEEDED') {
        throw new Error(`Textract job did not complete: ${status}`);
      }
      
      // Process blocks
      const blocks = result.Blocks || [];
      const textBlocks = blocks.filter(b => b.BlockType === 'LINE');
      const extractedText = textBlocks.map(b => b.Text).join('\n');
      const pageCount = Math.max(...textBlocks.map(b => b.Page || 1), 1);
      
      // Extract headings (simplified - lines that are short and capitalized)
      const headings = textBlocks
        .filter(b => b.Text && b.Text.length < 100 && b.Text === b.Text.toUpperCase())
        .map(b => b.Text || '')
        .slice(0, 10);
      
      // Count tables (simplified)
      const tableCount = blocks.filter(b => b.BlockType === 'TABLE').length;
      
      return {
        extractedText,
        pageCount,
        structure: {
          headings,
          tables: tableCount,
          images: 0, // Textract doesn't extract images
        },
      };
    } catch (error) {
      logger.warn('AWS Textract failed, using fallback', { error });
      return {
        extractedText: `[Document extraction unavailable for ${s3Uri}]`,
        pageCount: 1,
        structure: {
          headings: [],
          tables: 0,
          images: 0,
        },
      };
    }
  }
  
  // ==========================================================================
  // Auto-Bridging (Cross-Modal Condition Evaluation)
  // ==========================================================================
  
  /**
   * Auto-Bridge: Convert multimedia content to target modality for condition evaluation
   * 
   * Example: Text condition "contains('fire')" on a video stream
   * → Bridge uses sidecar.transcription or sidecar.description
   * → Evaluates condition against bridged text content
   */
  autoBridge(
    stream: MultimediaStream,
    targetModality: 'text' | 'vector'
  ): BridgeResult {
    const sourceModality = stream.mediaType;
    
    // Same modality - no bridging needed
    if (sourceModality === 'text' && targetModality === 'text') {
      return {
        bridged: false,
        sourceModality,
        targetModality,
        bridgeMethod: 'direct',
        content: stream.sidecar.transcription?.text || 
                 stream.sidecar.description?.detailed ||
                 stream.sidecar.documentContent?.extractedText,
        confidence: 1.0,
      };
    }
    
    // Text target - use transcription/description
    if (targetModality === 'text') {
      return this.bridgeToText(stream);
    }
    
    // Vector/embedding target - use pre-computed embedding
    if (targetModality === 'vector') {
      return this.bridgeToEmbedding(stream);
    }
    
    return {
      bridged: false,
      sourceModality,
      targetModality,
      bridgeMethod: 'direct',
      content: null,
      confidence: 0,
      warning: `Cannot bridge ${sourceModality} to ${targetModality}`,
    };
  }
  
  /**
   * Bridge any modality to text for text-based condition evaluation
   */
  private bridgeToText(stream: MultimediaStream): BridgeResult {
    const sidecar = stream.sidecar;
    
    // Priority: transcription > description > document content
    if (sidecar.transcription?.text) {
      return {
        bridged: true,
        sourceModality: stream.mediaType,
        targetModality: 'text',
        bridgeMethod: 'transcription',
        content: sidecar.transcription.text,
        confidence: sidecar.transcription.confidence,
      };
    }
    
    if (sidecar.description?.detailed) {
      return {
        bridged: true,
        sourceModality: stream.mediaType,
        targetModality: 'text',
        bridgeMethod: 'description',
        content: sidecar.description.detailed,
        confidence: 0.85, // Description is interpretation, not verbatim
      };
    }
    
    if (sidecar.documentContent?.extractedText) {
      return {
        bridged: true,
        sourceModality: stream.mediaType,
        targetModality: 'text',
        bridgeMethod: 'document_text',
        content: sidecar.documentContent.extractedText,
        confidence: 0.95,
      };
    }
    
    return {
      bridged: false,
      sourceModality: stream.mediaType,
      targetModality: 'text',
      bridgeMethod: 'direct',
      content: null,
      confidence: 0,
      warning: `No text representation available for ${stream.mediaType}`,
    };
  }
  
  /**
   * Bridge to embedding for semantic condition evaluation
   */
  private bridgeToEmbedding(stream: MultimediaStream): BridgeResult {
    if (stream.sidecar.embedding?.vector) {
      return {
        bridged: true,
        sourceModality: stream.mediaType,
        targetModality: 'text', // Use text as the base type for bridge result
        bridgeMethod: 'embedding',
        content: stream.sidecar.embedding.vector,
        confidence: 1.0,
      };
    }
    
    return {
      bridged: false,
      sourceModality: stream.mediaType,
      targetModality: 'text',
      bridgeMethod: 'embedding',
      content: null,
      confidence: 0,
      warning: `No embedding available for ${stream.mediaType}`,
    };
  }
  
  // ==========================================================================
  // Stream Synthesis (Director Pattern)
  // ==========================================================================
  
  /**
   * Synthesize multiple multimedia streams using the "Director" pattern
   * 
   * Logic: Visual content is the ANCHOR, text streams are ANNOTATIONS
   */
  async synthesizeStreams(
    streams: MultimediaStream[],
    synthesisPrompt?: string
  ): Promise<{ synthesized: string; confidence: number }> {
    // Find anchor (prefer video > image > audio > document > text)
    const priorityOrder: MediaType[] = ['video', 'image', 'audio', 'document', 'text'];
    const sortedStreams = [...streams].sort((a, b) => 
      priorityOrder.indexOf(a.mediaType) - priorityOrder.indexOf(b.mediaType)
    );
    
    const anchor = sortedStreams[0];
    const annotations = sortedStreams.slice(1);
    
    // Build context
    let anchorContext = '';
    if (anchor.mediaType === 'video' || anchor.mediaType === 'image') {
      anchorContext = anchor.sidecar.description?.detailed || 
                      anchor.sidecar.transcription?.text ||
                      '[Visual content]';
    } else {
      anchorContext = anchor.sidecar.transcription?.text ||
                      anchor.sidecar.documentContent?.extractedText ||
                      '[Content]';
    }
    
    const annotationTexts = annotations.map((s, i) => {
      const text = s.sidecar.transcription?.text ||
                   s.sidecar.description?.detailed ||
                   s.sidecar.documentContent?.extractedText ||
                   '[No text available]';
      return `Stream ${i + 2} (${s.mediaType}): ${text}`;
    }).join('\n\n');
    
    const prompt = synthesisPrompt || 'Synthesize these inputs into a coherent response.';
    
    const result = await modelRouterService.invoke({
      modelId: 'anthropic/claude-3-5-sonnet-20241022',
      messages: [{
        role: 'user',
        content: `${prompt}

**ANCHOR CONTENT (${anchor.mediaType})**:
${anchorContext}

**ANNOTATIONS**:
${annotationTexts || 'No additional annotations.'}

Provide a synthesized response that integrates all inputs coherently.`,
      }],
      maxTokens: 2048,
      temperature: 0.3,
    });
    
    return {
      synthesized: result.content,
      confidence: 0.85,
    };
  }
  
  // ==========================================================================
  // Utilities
  // ==========================================================================
  
  /**
   * Create a MultimediaStream from an upload
   */
  createMultimediaStream(
    sourceUri: string,
    mediaType: MediaType,
    sidecar: CognitiveSidecar,
    options?: {
      originalFilename?: string;
      uploadedBy?: string;
    }
  ): MultimediaStream {
    return {
      streamId: uuidv4(),
      mediaType,
      sourceUri,
      sidecar,
      originalFilename: options?.originalFilename,
      uploadedAt: new Date().toISOString(),
      uploadedBy: options?.uploadedBy,
    };
  }
  
  /**
   * Check if a sidecar is ready for use
   */
  isSidecarReady(sidecar: CognitiveSidecar): boolean {
    return sidecar.status === 'complete' || sidecar.status === 'partial';
  }
  
  /**
   * Get text representation from any sidecar
   */
  getTextRepresentation(sidecar: CognitiveSidecar): string | null {
    return sidecar.transcription?.text ||
           sidecar.description?.detailed ||
           sidecar.documentContent?.extractedText ||
           null;
  }
}

// Singleton export
export const multimediaSidecarService = new MultimediaSidecarService();

export default multimediaSidecarService;
