/**
 * RNIR (Radiant Neural Intermediate Representation) Types
 * 
 * Model-agnostic "cognitive source code" that can be compiled into:
 * - LoRA weights for self-hosted models (Cortex)
 * - System prompts for external APIs (OpenAI, Claude, etc.)
 * 
 * @version 1.0.0
 * @since v6.2.0
 */

// =============================================================================
// RNIR Core Types
// =============================================================================

/**
 * Single RNIR training example
 */
export interface RNIRExample {
  /** User input/prompt */
  user: string;
  
  /** Expected assistant response */
  assistant: string;
  
  /** Optional system context for this example */
  system?: string;
  
  /** Domain this example belongs to */
  domain?: string;
  
  /** Tags for categorization */
  tags?: string[];
  
  /** Quality score (0-1) */
  quality?: number;
  
  /** Source of this example (curator, manual, synthetic) */
  source?: 'curator' | 'manual' | 'synthetic' | 'imported';
  
  /** Metadata */
  metadata?: Record<string, unknown>;
}

/**
 * RNIR document (rnir.jsonl parsed)
 */
export interface RNIRDocument {
  /** Schema version */
  version: '1.0';
  
  /** Cartridge ID */
  cartridgeId: string;
  
  /** Domain this RNIR is for */
  domain: string;
  
  /** Training examples */
  examples: RNIRExample[];
  
  /** Total example count */
  exampleCount: number;
  
  /** Created timestamp */
  createdAt: string;
  
  /** Last modified timestamp */
  modifiedAt: string;
  
  /** Generated by (curator version, etc.) */
  generatedBy: string;
}

// =============================================================================
// Compilation Targets
// =============================================================================

/**
 * Target format for RNIR compilation
 */
export type RNIRCompilationTarget = 
  | 'lora'              // LoRA weights for fine-tuning
  | 'system_prompt'     // System prompt injection
  | 'few_shot'          // Few-shot examples
  | 'rag_chunks'        // RAG knowledge chunks
  | 'all';              // All formats

/**
 * Model family for compilation
 */
export type RNIRModelFamily = 
  | 'llama'             // Meta Llama models
  | 'qwen'              // Alibaba Qwen models
  | 'mistral'           // Mistral AI models
  | 'claude'            // Anthropic Claude (external)
  | 'gpt'               // OpenAI GPT (external)
  | 'gemini'            // Google Gemini (external)
  | 'universal';        // Generic format

/**
 * LoRA compilation settings
 */
export interface LoRACompilationSettings {
  /** Target model family */
  modelFamily: RNIRModelFamily;
  
  /** Specific model ID (e.g., "llama-3.1-8b") */
  modelId: string;
  
  /** LoRA rank (default: 16) */
  rank: number;
  
  /** LoRA alpha (default: 32) */
  alpha: number;
  
  /** Dropout (default: 0.05) */
  dropout: number;
  
  /** Target modules */
  targetModules: string[];
  
  /** Learning rate */
  learningRate: number;
  
  /** Epochs */
  epochs: number;
  
  /** Batch size */
  batchSize: number;
}

/**
 * System prompt compilation settings
 */
export interface SystemPromptCompilationSettings {
  /** Target model family */
  modelFamily: RNIRModelFamily;
  
  /** Maximum prompt length */
  maxLength: number;
  
  /** Include few-shot examples */
  includeFewShot: boolean;
  
  /** Number of few-shot examples */
  fewShotCount: number;
  
  /** Prompt template style */
  templateStyle: 'minimal' | 'detailed' | 'structured';
}

/**
 * Compilation request
 */
export interface RNIRCompilationRequest {
  /** Cartridge ID */
  cartridgeId: string;
  
  /** Target format */
  target: RNIRCompilationTarget;
  
  /** Model family */
  modelFamily: RNIRModelFamily;
  
  /** LoRA settings (if target is 'lora') */
  loraSettings?: LoRACompilationSettings;
  
  /** System prompt settings (if target is 'system_prompt') */
  systemPromptSettings?: SystemPromptCompilationSettings;
  
  /** Priority (1-10) */
  priority?: number;
}

// =============================================================================
// Compilation Results
// =============================================================================

/**
 * Compilation status
 */
export type RNIRCompilationStatus = 
  | 'pending'
  | 'queued'
  | 'compiling'
  | 'completed'
  | 'failed'
  | 'cancelled';

/**
 * Compiled artifact
 */
export interface RNIRCompiledArtifact {
  /** Artifact ID */
  id: string;
  
  /** Cartridge ID */
  cartridgeId: string;
  
  /** Compilation target */
  target: RNIRCompilationTarget;
  
  /** Model family */
  modelFamily: RNIRModelFamily;
  
  /** Specific model ID */
  modelId?: string;
  
  /** S3 path to artifact */
  artifactPath: string;
  
  /** Artifact size in bytes */
  sizeBytes: number;
  
  /** SHA-256 checksum */
  checksum: string;
  
  /** Status */
  status: RNIRCompilationStatus;
  
  /** Compilation started at */
  startedAt?: string;
  
  /** Compilation completed at */
  completedAt?: string;
  
  /** Error message if failed */
  errorMessage?: string;
  
  /** Compilation metrics */
  metrics?: {
    trainingLoss?: number;
    validationLoss?: number;
    examplesProcessed: number;
    compilationTimeSeconds: number;
  };
  
  /** Created timestamp */
  createdAt: string;
}

/**
 * Compilation job
 */
export interface RNIRCompilationJob {
  /** Job ID */
  id: string;
  
  /** Tenant ID */
  tenantId: string;
  
  /** Request */
  request: RNIRCompilationRequest;
  
  /** Status */
  status: RNIRCompilationStatus;
  
  /** Progress (0-100) */
  progress: number;
  
  /** Current step description */
  currentStep?: string;
  
  /** Artifacts produced */
  artifacts: RNIRCompiledArtifact[];
  
  /** Started at */
  startedAt?: string;
  
  /** Completed at */
  completedAt?: string;
  
  /** Error if failed */
  error?: string;
  
  /** Created at */
  createdAt: string;
}

// =============================================================================
// Admin Dashboard Types
// =============================================================================

/**
 * RNIR dashboard summary
 */
export interface RNIRDashboard {
  /** Total RNIR documents */
  totalDocuments: number;
  
  /** Total examples across all documents */
  totalExamples: number;
  
  /** Documents by domain */
  byDomain: Record<string, number>;
  
  /** Compilation jobs */
  compilationStats: {
    pending: number;
    inProgress: number;
    completed: number;
    failed: number;
  };
  
  /** Recent compilations */
  recentCompilations: RNIRCompilationJob[];
  
  /** Compiled artifacts by target */
  artifactsByTarget: Record<RNIRCompilationTarget, number>;
  
  /** Storage used (bytes) */
  storageUsedBytes: number;
}

/**
 * RNIR document preview (for UI)
 */
export interface RNIRDocumentPreview {
  cartridgeId: string;
  cartridgeName: string;
  domain: string;
  exampleCount: number;
  sampleExamples: RNIRExample[];
  hasLoraArtifact: boolean;
  hasPromptArtifact: boolean;
  lastCompiled?: string;
}

// =============================================================================
// Cortex Integration (from v4.21.0 spec)
// =============================================================================

/**
 * Knowledge density from Cortex for RNIR compilation decisions
 * Aligned with cortex-intelligence.service.ts
 */
export interface RNIRKnowledgeDensity {
  /** Total graph nodes for this domain */
  totalNodes: number;
  
  /** Total graph edges */
  totalEdges: number;
  
  /** Knowledge depth classification */
  knowledgeDepth: 'none' | 'sparse' | 'moderate' | 'rich' | 'expert';
  
  /** Confidence boost from existing knowledge (0.0-0.3) */
  confidenceBoost: number;
  
  /** Top domains with most knowledge */
  topDomains: string[];
  
  /** Key entities from graph */
  keyEntities: string[];
}

/**
 * Cortex-aware compilation that considers existing knowledge
 */
export interface RNIRCortexAwareCompilation {
  /** Should use existing Cortex knowledge? */
  useCortexKnowledge: boolean;
  
  /** Knowledge density assessment */
  knowledgeDensity: RNIRKnowledgeDensity;
  
  /** Nodes to incorporate from Cortex warm tier */
  incorporateNodeIds?: string[];
  
  /** Max nodes to use (per orchestration recommendation) */
  maxNodes: number;
  
  /** Domain boost from Cortex */
  domainBoosts: Record<string, number>;
}

// =============================================================================
// Twilight Dreaming Integration (from v4.21.0 spec)
// =============================================================================

/**
 * Twilight Dreaming task for RNIR compilation
 * Runs during off-hours (nightly 2am UTC)
 */
export type TwilightTaskType = 
  | 'compile_lora'       // Heavy LoRA training
  | 'generate_rnir'      // Extract RNIR from Curator
  | 'optimize_prompts'   // Optimize system prompts
  | 'infer_examples'     // Generate synthetic examples
  | 'merge_domains';     // Merge overlapping domain knowledge

export interface RnirTwilightTask {
  /** Task ID */
  taskId: string;
  
  /** Tenant ID */
  tenantId: string;
  
  /** Task type */
  taskType: TwilightTaskType;
  
  /** Priority (1-10, higher = more important) */
  priority: number;
  
  /** Scope of task */
  scope: 'local' | 'domain' | 'global';
  
  /** Input parameters */
  parameters: Record<string, unknown>;
  
  /** Scheduled time */
  scheduledAt: string;
  
  /** Status */
  status: 'scheduled' | 'running' | 'completed' | 'failed' | 'cancelled';
  
  /** Started at */
  startedAt?: string;
  
  /** Completed at */
  completedAt?: string;
  
  /** Result summary */
  result?: RnirTwilightResult;
  
  /** Error if failed */
  error?: string;
}

export interface RnirTwilightResult {
  /** Artifacts created */
  artifactsCreated: number;
  
  /** Examples processed */
  examplesProcessed: number;
  
  /** Bytes processed */
  bytesProcessed: number;
  
  /** Duration in seconds */
  durationSeconds: number;
  
  /** Estimated cost */
  estimatedCostCents: number;
  
  /** Improvement metrics */
  improvements?: {
    accuracyDelta?: number;
    tokensSaved?: number;
    latencyReduction?: number;
  };
}

/**
 * Schedule RNIR compilation for Twilight Dreaming
 */
export interface ScheduleTwilightRNIRRequest {
  /** Cartridge ID */
  cartridgeId: string;
  
  /** Task type */
  taskType: TwilightTaskType;
  
  /** Priority (1-10) */
  priority?: number;
  
  /** Target model family */
  modelFamily?: RNIRModelFamily;
  
  /** Run immediately (bypass scheduling)? */
  runImmediately?: boolean;
}

// =============================================================================
// Axiom Domain Signatures (from v4.21.0 spec)
// =============================================================================

/**
 * Domain signature for RNIR compilation
 * Aligned with Axiom domain signatures
 */
export interface RNIRDomainSignature {
  /** Domain ID (e.g., "legal.contracts.saas") */
  domainId: string;
  
  /** Role template for this domain */
  roleTemplate: string;
  
  /** Template parameters */
  roleParameters: Record<string, string>;
  
  /** Required context fields */
  requiredContext: string[];
  
  /** Domain-specific constraints */
  domainConstraints: string[];
  
  /** Output format specification */
  outputFormat: string;
  
  /** Model preferences for this domain */
  modelPreferences: {
    primaryModel: string;
    requiredProficiencies: Record<string, number>;
    fallbackChain: string[];
    thinkingMethod: 'standard' | 'extended' | 'budget';
  };
  
  /** Model-specific prompt variants */
  modelVariants: {
    claude?: string;
    gpt?: string;
    gemini?: string;
    llama?: string;
    qwen?: string;
    mistral?: string;
  };
}

// =============================================================================
// Curator Integration
// =============================================================================

/**
 * Generate RNIR from Curator knowledge
 */
export interface GenerateRNIRRequest {
  /** Cartridge ID to generate for */
  cartridgeId: string;
  
  /** Domains to include */
  domains?: string[];
  
  /** Minimum quality score for examples */
  minQuality?: number;
  
  /** Maximum examples per domain */
  maxExamplesPerDomain?: number;
  
  /** Include synthetic examples */
  includeSynthetic?: boolean;
  
  /** Overwrite existing RNIR */
  overwrite?: boolean;
}

/**
 * Generate RNIR result
 */
export interface GenerateRNIRResult {
  /** Success */
  success: boolean;
  
  /** Cartridge ID */
  cartridgeId: string;
  
  /** Examples generated */
  examplesGenerated: number;
  
  /** Examples by domain */
  examplesByDomain: Record<string, number>;
  
  /** Warnings */
  warnings: string[];
  
  /** RNIR document location */
  rnirPath?: string;
}
