/** @type {import('jest').Config} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/__tests__'],
  testMatch: ['**/*.test.ts'],
  testPathIgnorePatterns: [
    '/node_modules/',
    // Tests with API mismatches - need maintenance (see TECH-DEBT.md)
    'agi-brain-planner.service.test.ts',
    'consciousness-middleware.service.test.ts',
    'user-registry.service.test.ts',
    'formal-reasoning.service.test.ts',
    'ego-context.service.test.ts',
    'security-protection.service.test.ts',
    'db-context.service.test.ts',
    'ai-reports.handler.test.ts',
    'economic-governor.service.test.ts',
    'mission-control.test.ts',
    'orchestration-rls.service.test.ts',
    '/integration/',
    '/cato/',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  transform: {
    '^.+\\.tsx?$': ['ts-jest', {
      tsconfig: {
        module: 'commonjs',
        target: 'ES2020',
        esModuleInterop: true,
        skipLibCheck: true,
        strict: true,
        moduleResolution: 'node',
        resolveJsonModule: true,
        declaration: false,
        declarationMap: false,
        outDir: './dist',
        rootDir: '.',
        baseUrl: '.',
        paths: {
          '@radiant/shared/*': ['../shared/src/*'],
        },
      },
    }],
  },
  moduleNameMapper: {
    '^@radiant/shared/(.*)$': '<rootDir>/../shared/src/$1',
  },
  collectCoverageFrom: [
    'lambda/**/*.ts',
    '!lambda/**/*.d.ts',
    '!lambda/**/index.ts',
  ],
  coverageDirectory: '<rootDir>/coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  testTimeout: 30000,
  verbose: true,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};
