/**
 * Scientific Computing Models - Protein folding, embeddings, math reasoning
 */

import { SageMakerModelConfig } from './index';

export const SCIENTIFIC_MODELS: SageMakerModelConfig[] = [
  {
    id: 'alphafold2',
    name: 'alphafold2',
    displayName: 'AlphaFold 2',
    description: 'Protein structure prediction with near-experimental accuracy',
    category: 'scientific_protein',
    specialty: 'protein_folding',
    image: 'pytorch-inference:2.1-gpu-py310-cu121-ubuntu22.04',
    instanceType: 'ml.g5.12xlarge',
    environment: { MODEL_NAME: 'alphafold2_ptm', JAX_PLATFORM_NAME: 'gpu' },
    parameters: 93_000_000,
    accuracy: 'GDT > 90 on CASP14',
    capabilities: ['protein_folding', 'structure_prediction', 'confidence_estimation'],
    inputFormats: ['text/fasta', 'text/plain'],
    outputFormats: ['application/pdb', 'application/mmcif', 'application/json'],
    thermal: { defaultState: 'OFF', scaleToZeroAfterMinutes: 10, warmupTimeSeconds: 180, minInstances: 0, maxInstances: 2 },
    license: 'Apache-2.0',
    pricing: { hourlyRate: 14.28, perRequest: 2.00, markup: 0.75 },
    minTier: 4, requiresGPU: true, gpuMemoryGB: 96, status: 'active',
  },
  {
    id: 'esm2-3b',
    name: 'esm2-3b',
    displayName: 'ESM-2 3B',
    description: 'Protein language model for embeddings and analysis',
    category: 'scientific_protein',
    specialty: 'protein_embeddings',
    image: 'pytorch-inference:2.1-transformers4.36-gpu-py310-cu121-ubuntu22.04',
    instanceType: 'ml.g5.4xlarge',
    environment: { HF_MODEL_ID: 'facebook/esm2_t36_3B_UR50D' },
    parameters: 3_000_000_000,
    capabilities: ['protein_embedding', 'sequence_analysis', 'structure_prediction'],
    inputFormats: ['text/fasta', 'text/plain'],
    outputFormats: ['application/json'],
    thermal: { defaultState: 'OFF', scaleToZeroAfterMinutes: 10, warmupTimeSeconds: 120, minInstances: 0, maxInstances: 2 },
    license: 'MIT',
    pricing: { hourlyRate: 3.55, perRequest: 0.50, markup: 0.75 },
    minTier: 4, requiresGPU: true, gpuMemoryGB: 20, status: 'active',
  },
  {
    id: 'alphageometry',
    name: 'alphageometry',
    displayName: 'AlphaGeometry',
    description: 'Olympiad-level geometry problem solver',
    category: 'scientific_math',
    specialty: 'geometry_reasoning',
    image: 'pytorch-inference:2.1-gpu-py310-cu121-ubuntu22.04',
    instanceType: 'ml.g5.2xlarge',
    environment: { MODEL_NAME: 'alphageometry' },
    parameters: 150_000_000,
    accuracy: '25/30 IMO geometry problems',
    capabilities: ['geometry_solving', 'proof_generation', 'theorem_proving'],
    inputFormats: ['application/json', 'text/plain'],
    outputFormats: ['application/json', 'text/plain'],
    thermal: { defaultState: 'OFF', scaleToZeroAfterMinutes: 10, warmupTimeSeconds: 90, minInstances: 0, maxInstances: 2 },
    license: 'Apache-2.0',
    pricing: { hourlyRate: 2.66, perRequest: 0.30, markup: 0.75 },
    minTier: 4, requiresGPU: true, gpuMemoryGB: 16, status: 'active',
  },
  {
    id: 'protenix',
    name: 'protenix',
    displayName: 'Protenix',
    description: 'Open-source AlphaFold3-like structure prediction',
    category: 'scientific_protein',
    specialty: 'protein_folding',
    image: 'pytorch-inference:2.1-gpu-py310-cu121-ubuntu22.04',
    instanceType: 'ml.g5.12xlarge',
    environment: { MODEL_NAME: 'protenix' },
    parameters: 0,
    capabilities: ['protein_folding', 'dna_rna_binding', 'ligand_binding', 'multi_chain'],
    inputFormats: ['text/fasta', 'application/json'],
    outputFormats: ['application/pdb', 'application/mmcif', 'application/json'],
    thermal: { defaultState: 'OFF', scaleToZeroAfterMinutes: 10, warmupTimeSeconds: 180, minInstances: 0, maxInstances: 2 },
    license: 'Apache-2.0',
    pricing: { hourlyRate: 14.28, perRequest: 2.50, markup: 0.75 },
    minTier: 4, requiresGPU: true, gpuMemoryGB: 96, status: 'beta',
  },
];
