// RADIANT v4.18.0 - Liquid Interface Component Registry
// "The Lego Protocol" - 50+ pre-built morphable components
// Components render from JSON schema, not generated code

import {
  LiquidComponent,
  ComponentCategory,
  ComponentRegistry,
  CategoryInfo,
  JSONSchema,
} from '@radiant/shared';

// ============================================================================
// Component Definitions (50+ Components)
// ============================================================================

const COMPONENTS: LiquidComponent[] = [
  // ---------------------------------------------------------------------------
  // DATA COMPONENTS (10)
  // ---------------------------------------------------------------------------
  {
    id: 'data-grid',
    name: 'DataGrid',
    category: 'data',
    description: 'Powerful spreadsheet-like grid with sorting, filtering, and editing',
    propsSchema: {
      type: 'object',
      properties: {
        columns: { type: 'array', description: 'Column definitions' },
        rows: { type: 'array', description: 'Row data' },
        editable: { type: 'boolean', default: false },
        sortable: { type: 'boolean', default: true },
        filterable: { type: 'boolean', default: true },
        pagination: { type: 'boolean', default: true },
        pageSize: { type: 'number', default: 25 },
      },
      required: ['columns', 'rows'],
    },
    eventsSchema: {
      type: 'object',
      properties: {
        onRowSelect: { type: 'object', description: 'Row selected' },
        onCellEdit: { type: 'object', description: 'Cell value changed' },
        onSort: { type: 'object', description: 'Sort changed' },
        onFilter: { type: 'object', description: 'Filter applied' },
      },
    },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 800, height: 500 },
    resizable: true,
    icon: '📊',
    color: '#3B82F6',
    tags: ['spreadsheet', 'table', 'excel', 'data'],
  },
  {
    id: 'pivot-table',
    name: 'PivotTable',
    category: 'data',
    description: 'Pivot table for data aggregation and analysis',
    propsSchema: {
      type: 'object',
      properties: {
        data: { type: 'array' },
        rows: { type: 'array', description: 'Row grouping fields' },
        columns: { type: 'array', description: 'Column grouping fields' },
        values: { type: 'array', description: 'Value aggregation fields' },
        aggregation: { type: 'string', enum: ['sum', 'avg', 'count', 'min', 'max'] },
      },
      required: ['data'],
    },
    eventsSchema: { type: 'object', properties: { onDrillDown: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 700, height: 450 },
    resizable: true,
    icon: '🔢',
    color: '#8B5CF6',
    tags: ['pivot', 'aggregation', 'analysis'],
  },
  {
    id: 'data-card',
    name: 'DataCard',
    category: 'data',
    description: 'Summary card with key metric',
    propsSchema: {
      type: 'object',
      properties: {
        title: { type: 'string' },
        value: { type: 'string' },
        change: { type: 'number' },
        changeLabel: { type: 'string' },
        icon: { type: 'string' },
        trend: { type: 'string', enum: ['up', 'down', 'neutral'] },
      },
      required: ['title', 'value'],
    },
    eventsSchema: { type: 'object', properties: { onClick: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: false,
    defaultSize: { width: 250, height: 120 },
    resizable: false,
    icon: '📈',
    color: '#10B981',
    tags: ['metric', 'kpi', 'summary'],
  },
  {
    id: 'json-viewer',
    name: 'JSONViewer',
    category: 'data',
    description: 'Interactive JSON tree viewer',
    propsSchema: {
      type: 'object',
      properties: {
        data: { type: 'object' },
        collapsed: { type: 'boolean', default: false },
        theme: { type: 'string', enum: ['light', 'dark'] },
      },
      required: ['data'],
    },
    eventsSchema: { type: 'object', properties: { onNodeSelect: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 500, height: 400 },
    resizable: true,
    icon: '🔍',
    color: '#F59E0B',
    tags: ['json', 'tree', 'inspector'],
  },
  {
    id: 'sql-viewer',
    name: 'SQLViewer',
    category: 'data',
    description: 'SQL query results viewer with export',
    propsSchema: {
      type: 'object',
      properties: {
        query: { type: 'string' },
        results: { type: 'array' },
        executionTime: { type: 'number' },
        rowCount: { type: 'number' },
      },
      required: ['results'],
    },
    eventsSchema: { type: 'object', properties: { onExport: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 700, height: 400 },
    resizable: true,
    icon: '🗄️',
    color: '#6366F1',
    tags: ['sql', 'database', 'query'],
  },
  {
    id: 'csv-editor',
    name: 'CSVEditor',
    category: 'data',
    description: 'CSV file editor with import/export',
    propsSchema: {
      type: 'object',
      properties: {
        content: { type: 'string' },
        delimiter: { type: 'string', default: ',' },
        hasHeader: { type: 'boolean', default: true },
      },
    },
    eventsSchema: { type: 'object', properties: { onChange: { type: 'object' }, onExport: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 800, height: 500 },
    resizable: true,
    icon: '📄',
    color: '#22C55E',
    tags: ['csv', 'excel', 'import'],
  },
  {
    id: 'data-filter',
    name: 'DataFilter',
    category: 'data',
    description: 'Advanced filter builder',
    propsSchema: {
      type: 'object',
      properties: {
        fields: { type: 'array' },
        filters: { type: 'array' },
        operators: { type: 'array' },
      },
      required: ['fields'],
    },
    eventsSchema: { type: 'object', properties: { onFilterChange: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 400, height: 300 },
    resizable: true,
    icon: '🔧',
    color: '#EC4899',
    tags: ['filter', 'query', 'search'],
  },
  {
    id: 'schema-designer',
    name: 'SchemaDesigner',
    category: 'data',
    description: 'Visual database schema designer',
    propsSchema: {
      type: 'object',
      properties: {
        tables: { type: 'array' },
        relationships: { type: 'array' },
      },
    },
    eventsSchema: { type: 'object', properties: { onSchemaChange: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 900, height: 600 },
    resizable: true,
    icon: '🏗️',
    color: '#14B8A6',
    tags: ['schema', 'erd', 'database'],
  },
  {
    id: 'data-diff',
    name: 'DataDiff',
    category: 'data',
    description: 'Compare two datasets side by side',
    propsSchema: {
      type: 'object',
      properties: {
        left: { type: 'array' },
        right: { type: 'array' },
        keyField: { type: 'string' },
      },
      required: ['left', 'right'],
    },
    eventsSchema: { type: 'object', properties: { onDiffSelect: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 900, height: 500 },
    resizable: true,
    icon: '⚖️',
    color: '#F97316',
    tags: ['diff', 'compare', 'merge'],
  },
  {
    id: 'data-import',
    name: 'DataImport',
    category: 'data',
    description: 'Data import wizard with mapping',
    propsSchema: {
      type: 'object',
      properties: {
        targetSchema: { type: 'object' },
        supportedFormats: { type: 'array' },
      },
    },
    eventsSchema: { type: 'object', properties: { onImportComplete: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 600, height: 500 },
    resizable: true,
    icon: '📥',
    color: '#06B6D4',
    tags: ['import', 'wizard', 'mapping'],
  },

  // ---------------------------------------------------------------------------
  // VISUALIZATION COMPONENTS (10)
  // ---------------------------------------------------------------------------
  {
    id: 'line-chart',
    name: 'LineChart',
    category: 'visualization',
    description: 'Line chart for time series data',
    propsSchema: {
      type: 'object',
      properties: {
        data: { type: 'array' },
        xAxis: { type: 'string' },
        yAxis: { type: 'array' },
        colors: { type: 'array' },
        showLegend: { type: 'boolean', default: true },
        animate: { type: 'boolean', default: true },
      },
      required: ['data', 'xAxis', 'yAxis'],
    },
    eventsSchema: { type: 'object', properties: { onPointClick: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 600, height: 400 },
    resizable: true,
    icon: '📈',
    color: '#3B82F6',
    tags: ['chart', 'line', 'timeseries'],
  },
  {
    id: 'bar-chart',
    name: 'BarChart',
    category: 'visualization',
    description: 'Bar chart for categorical data',
    propsSchema: {
      type: 'object',
      properties: {
        data: { type: 'array' },
        xAxis: { type: 'string' },
        yAxis: { type: 'string' },
        orientation: { type: 'string', enum: ['vertical', 'horizontal'] },
        stacked: { type: 'boolean', default: false },
      },
      required: ['data', 'xAxis', 'yAxis'],
    },
    eventsSchema: { type: 'object', properties: { onBarClick: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 600, height: 400 },
    resizable: true,
    icon: '📊',
    color: '#10B981',
    tags: ['chart', 'bar', 'categorical'],
  },
  {
    id: 'pie-chart',
    name: 'PieChart',
    category: 'visualization',
    description: 'Pie/donut chart for proportions',
    propsSchema: {
      type: 'object',
      properties: {
        data: { type: 'array' },
        labelField: { type: 'string' },
        valueField: { type: 'string' },
        donut: { type: 'boolean', default: false },
        showLabels: { type: 'boolean', default: true },
      },
      required: ['data', 'labelField', 'valueField'],
    },
    eventsSchema: { type: 'object', properties: { onSliceClick: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 400, height: 400 },
    resizable: true,
    icon: '🥧',
    color: '#F59E0B',
    tags: ['chart', 'pie', 'donut'],
  },
  {
    id: 'scatter-plot',
    name: 'ScatterPlot',
    category: 'visualization',
    description: 'Scatter plot for correlation analysis',
    propsSchema: {
      type: 'object',
      properties: {
        data: { type: 'array' },
        xField: { type: 'string' },
        yField: { type: 'string' },
        sizeField: { type: 'string' },
        colorField: { type: 'string' },
        trendline: { type: 'boolean', default: false },
      },
      required: ['data', 'xField', 'yField'],
    },
    eventsSchema: { type: 'object', properties: { onPointClick: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 600, height: 500 },
    resizable: true,
    icon: '🔵',
    color: '#8B5CF6',
    tags: ['chart', 'scatter', 'correlation'],
  },
  {
    id: 'area-chart',
    name: 'AreaChart',
    category: 'visualization',
    description: 'Area chart for cumulative data',
    propsSchema: {
      type: 'object',
      properties: {
        data: { type: 'array' },
        xAxis: { type: 'string' },
        yAxis: { type: 'array' },
        stacked: { type: 'boolean', default: false },
        gradient: { type: 'boolean', default: true },
      },
      required: ['data', 'xAxis', 'yAxis'],
    },
    eventsSchema: { type: 'object', properties: { onAreaClick: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 600, height: 400 },
    resizable: true,
    icon: '📉',
    color: '#06B6D4',
    tags: ['chart', 'area', 'cumulative'],
  },
  {
    id: 'heatmap',
    name: 'Heatmap',
    category: 'visualization',
    description: 'Heatmap for matrix data',
    propsSchema: {
      type: 'object',
      properties: {
        data: { type: 'array' },
        xLabels: { type: 'array' },
        yLabels: { type: 'array' },
        colorScale: { type: 'string', enum: ['sequential', 'diverging'] },
      },
      required: ['data'],
    },
    eventsSchema: { type: 'object', properties: { onCellClick: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 600, height: 500 },
    resizable: true,
    icon: '🔥',
    color: '#EF4444',
    tags: ['chart', 'heatmap', 'matrix'],
  },
  {
    id: 'treemap',
    name: 'Treemap',
    category: 'visualization',
    description: 'Treemap for hierarchical data',
    propsSchema: {
      type: 'object',
      properties: {
        data: { type: 'object' },
        valueField: { type: 'string' },
        labelField: { type: 'string' },
      },
      required: ['data'],
    },
    eventsSchema: { type: 'object', properties: { onNodeClick: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 600, height: 500 },
    resizable: true,
    icon: '🌲',
    color: '#22C55E',
    tags: ['chart', 'treemap', 'hierarchy'],
  },
  {
    id: 'geo-map',
    name: 'GeoMap',
    category: 'visualization',
    description: 'Geographic map with markers',
    propsSchema: {
      type: 'object',
      properties: {
        center: { type: 'object' },
        zoom: { type: 'number', default: 10 },
        markers: { type: 'array' },
        regions: { type: 'array' },
        mapStyle: { type: 'string' },
      },
    },
    eventsSchema: { type: 'object', properties: { onMarkerClick: { type: 'object' }, onRegionClick: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 700, height: 500 },
    resizable: true,
    icon: '🗺️',
    color: '#14B8A6',
    tags: ['map', 'geo', 'location'],
  },
  {
    id: 'timeline',
    name: 'Timeline',
    category: 'visualization',
    description: 'Timeline for chronological events',
    propsSchema: {
      type: 'object',
      properties: {
        events: { type: 'array' },
        orientation: { type: 'string', enum: ['horizontal', 'vertical'] },
        showLabels: { type: 'boolean', default: true },
      },
      required: ['events'],
    },
    eventsSchema: { type: 'object', properties: { onEventClick: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 800, height: 300 },
    resizable: true,
    icon: '📅',
    color: '#EC4899',
    tags: ['timeline', 'chronological', 'events'],
  },
  {
    id: 'sankey',
    name: 'SankeyDiagram',
    category: 'visualization',
    description: 'Sankey diagram for flow visualization',
    propsSchema: {
      type: 'object',
      properties: {
        nodes: { type: 'array' },
        links: { type: 'array' },
      },
      required: ['nodes', 'links'],
    },
    eventsSchema: { type: 'object', properties: { onLinkClick: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 700, height: 500 },
    resizable: true,
    icon: '🌊',
    color: '#6366F1',
    tags: ['sankey', 'flow', 'diagram'],
  },

  // ---------------------------------------------------------------------------
  // PRODUCTIVITY COMPONENTS (10)
  // ---------------------------------------------------------------------------
  {
    id: 'kanban',
    name: 'KanbanBoard',
    category: 'productivity',
    description: 'Kanban board with drag-and-drop',
    propsSchema: {
      type: 'object',
      properties: {
        columns: { type: 'array' },
        cards: { type: 'array' },
        allowAdd: { type: 'boolean', default: true },
        allowEdit: { type: 'boolean', default: true },
      },
      required: ['columns', 'cards'],
    },
    eventsSchema: { type: 'object', properties: { onCardMove: { type: 'object' }, onCardAdd: { type: 'object' }, onCardEdit: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 900, height: 600 },
    resizable: true,
    icon: '📋',
    color: '#3B82F6',
    tags: ['kanban', 'board', 'tasks', 'trello'],
  },
  {
    id: 'calendar',
    name: 'Calendar',
    category: 'productivity',
    description: 'Calendar with event management',
    propsSchema: {
      type: 'object',
      properties: {
        events: { type: 'array' },
        view: { type: 'string', enum: ['month', 'week', 'day', 'agenda'] },
        editable: { type: 'boolean', default: true },
      },
    },
    eventsSchema: { type: 'object', properties: { onEventClick: { type: 'object' }, onDateSelect: { type: 'object' }, onEventDrop: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 800, height: 600 },
    resizable: true,
    icon: '📆',
    color: '#10B981',
    tags: ['calendar', 'schedule', 'events'],
  },
  {
    id: 'gantt',
    name: 'GanttChart',
    category: 'productivity',
    description: 'Gantt chart for project timelines',
    propsSchema: {
      type: 'object',
      properties: {
        tasks: { type: 'array' },
        dependencies: { type: 'array' },
        viewMode: { type: 'string', enum: ['day', 'week', 'month'] },
      },
      required: ['tasks'],
    },
    eventsSchema: { type: 'object', properties: { onTaskClick: { type: 'object' }, onTaskUpdate: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 900, height: 500 },
    resizable: true,
    icon: '📊',
    color: '#F59E0B',
    tags: ['gantt', 'project', 'timeline'],
  },
  {
    id: 'todo-list',
    name: 'TodoList',
    category: 'productivity',
    description: 'Todo list with completion tracking',
    propsSchema: {
      type: 'object',
      properties: {
        items: { type: 'array' },
        allowAdd: { type: 'boolean', default: true },
        showCompleted: { type: 'boolean', default: true },
        groupBy: { type: 'string' },
      },
    },
    eventsSchema: { type: 'object', properties: { onItemToggle: { type: 'object' }, onItemAdd: { type: 'object' }, onItemDelete: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 400, height: 500 },
    resizable: true,
    icon: '✅',
    color: '#22C55E',
    tags: ['todo', 'tasks', 'checklist'],
  },
  {
    id: 'notes',
    name: 'NotesEditor',
    category: 'productivity',
    description: 'Rich text notes editor',
    propsSchema: {
      type: 'object',
      properties: {
        content: { type: 'string' },
        placeholder: { type: 'string' },
        toolbar: { type: 'array' },
      },
    },
    eventsSchema: { type: 'object', properties: { onChange: { type: 'object' }, onSave: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 600, height: 500 },
    resizable: true,
    icon: '📝',
    color: '#8B5CF6',
    tags: ['notes', 'editor', 'markdown'],
  },
  {
    id: 'timer',
    name: 'Timer',
    category: 'productivity',
    description: 'Countdown/stopwatch timer',
    propsSchema: {
      type: 'object',
      properties: {
        mode: { type: 'string', enum: ['countdown', 'stopwatch'] },
        duration: { type: 'number' },
        autoStart: { type: 'boolean', default: false },
      },
    },
    eventsSchema: { type: 'object', properties: { onComplete: { type: 'object' }, onTick: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 300, height: 200 },
    resizable: false,
    icon: '⏱️',
    color: '#EF4444',
    tags: ['timer', 'pomodoro', 'countdown'],
  },
  {
    id: 'habit-tracker',
    name: 'HabitTracker',
    category: 'productivity',
    description: 'Habit tracking with streaks',
    propsSchema: {
      type: 'object',
      properties: {
        habits: { type: 'array' },
        history: { type: 'object' },
        showStreaks: { type: 'boolean', default: true },
      },
    },
    eventsSchema: { type: 'object', properties: { onHabitToggle: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 500, height: 400 },
    resizable: true,
    icon: '🎯',
    color: '#06B6D4',
    tags: ['habits', 'tracker', 'streaks'],
  },
  {
    id: 'mindmap',
    name: 'MindMap',
    category: 'productivity',
    description: 'Mind map for brainstorming',
    propsSchema: {
      type: 'object',
      properties: {
        nodes: { type: 'array' },
        connections: { type: 'array' },
        centerNode: { type: 'object' },
      },
    },
    eventsSchema: { type: 'object', properties: { onNodeAdd: { type: 'object' }, onNodeEdit: { type: 'object' }, onConnect: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 800, height: 600 },
    resizable: true,
    icon: '🧠',
    color: '#EC4899',
    tags: ['mindmap', 'brainstorm', 'ideas'],
  },
  {
    id: 'whiteboard',
    name: 'Whiteboard',
    category: 'productivity',
    description: 'Collaborative whiteboard canvas',
    propsSchema: {
      type: 'object',
      properties: {
        elements: { type: 'array' },
        background: { type: 'string' },
        gridEnabled: { type: 'boolean', default: true },
      },
    },
    eventsSchema: { type: 'object', properties: { onDraw: { type: 'object' }, onElementAdd: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 900, height: 600 },
    resizable: true,
    icon: '🎨',
    color: '#14B8A6',
    tags: ['whiteboard', 'draw', 'canvas'],
  },
  {
    id: 'file-manager',
    name: 'FileManager',
    category: 'productivity',
    description: 'File browser and manager',
    propsSchema: {
      type: 'object',
      properties: {
        files: { type: 'array' },
        currentPath: { type: 'string' },
        viewMode: { type: 'string', enum: ['list', 'grid'] },
      },
    },
    eventsSchema: { type: 'object', properties: { onFileSelect: { type: 'object' }, onNavigate: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 700, height: 500 },
    resizable: true,
    icon: '📁',
    color: '#F97316',
    tags: ['files', 'browser', 'explorer'],
  },

  // ---------------------------------------------------------------------------
  // FINANCE COMPONENTS (6)
  // ---------------------------------------------------------------------------
  {
    id: 'invoice',
    name: 'Invoice',
    category: 'finance',
    description: 'Invoice generator and viewer',
    propsSchema: {
      type: 'object',
      properties: {
        invoiceNumber: { type: 'string' },
        client: { type: 'object' },
        items: { type: 'array' },
        taxRate: { type: 'number' },
        currency: { type: 'string', default: 'USD' },
        dueDate: { type: 'string' },
        status: { type: 'string', enum: ['draft', 'sent', 'paid', 'overdue'] },
      },
      required: ['items'],
    },
    eventsSchema: { type: 'object', properties: { onSend: { type: 'object' }, onExport: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 700, height: 800 },
    resizable: true,
    icon: '🧾',
    color: '#3B82F6',
    tags: ['invoice', 'billing', 'freelance'],
  },
  {
    id: 'budget-tracker',
    name: 'BudgetTracker',
    category: 'finance',
    description: 'Budget tracking with categories',
    propsSchema: {
      type: 'object',
      properties: {
        budget: { type: 'number' },
        spent: { type: 'number' },
        categories: { type: 'array' },
        period: { type: 'string', enum: ['weekly', 'monthly', 'yearly'] },
      },
    },
    eventsSchema: { type: 'object', properties: { onTransactionAdd: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 500, height: 400 },
    resizable: true,
    icon: '💰',
    color: '#10B981',
    tags: ['budget', 'spending', 'finance'],
  },
  {
    id: 'expense-table',
    name: 'ExpenseTable',
    category: 'finance',
    description: 'Expense tracking table',
    propsSchema: {
      type: 'object',
      properties: {
        expenses: { type: 'array' },
        categories: { type: 'array' },
        dateRange: { type: 'object' },
      },
    },
    eventsSchema: { type: 'object', properties: { onExpenseAdd: { type: 'object' }, onExpenseEdit: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 700, height: 500 },
    resizable: true,
    icon: '💳',
    color: '#EF4444',
    tags: ['expenses', 'transactions', 'tracking'],
  },
  {
    id: 'portfolio',
    name: 'Portfolio',
    category: 'finance',
    description: 'Investment portfolio tracker',
    propsSchema: {
      type: 'object',
      properties: {
        holdings: { type: 'array' },
        totalValue: { type: 'number' },
        showCharts: { type: 'boolean', default: true },
      },
    },
    eventsSchema: { type: 'object', properties: { onHoldingClick: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 800, height: 600 },
    resizable: true,
    icon: '📈',
    color: '#8B5CF6',
    tags: ['portfolio', 'stocks', 'investments'],
  },
  {
    id: 'calculator',
    name: 'Calculator',
    category: 'finance',
    description: 'Scientific calculator',
    propsSchema: {
      type: 'object',
      properties: {
        mode: { type: 'string', enum: ['basic', 'scientific', 'programmer'] },
        memory: { type: 'array' },
      },
    },
    eventsSchema: { type: 'object', properties: { onCalculate: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 350, height: 500 },
    resizable: false,
    icon: '🔢',
    color: '#6366F1',
    tags: ['calculator', 'math', 'compute'],
  },
  {
    id: 'currency-converter',
    name: 'CurrencyConverter',
    category: 'finance',
    description: 'Currency conversion tool',
    propsSchema: {
      type: 'object',
      properties: {
        fromCurrency: { type: 'string' },
        toCurrency: { type: 'string' },
        amount: { type: 'number' },
        rates: { type: 'object' },
      },
    },
    eventsSchema: { type: 'object', properties: { onConvert: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 400, height: 300 },
    resizable: false,
    icon: '💱',
    color: '#22C55E',
    tags: ['currency', 'conversion', 'forex'],
  },

  // ---------------------------------------------------------------------------
  // CODE COMPONENTS (6)
  // ---------------------------------------------------------------------------
  {
    id: 'code-editor',
    name: 'CodeEditor',
    category: 'code',
    description: 'Monaco-based code editor',
    propsSchema: {
      type: 'object',
      properties: {
        code: { type: 'string' },
        language: { type: 'string' },
        theme: { type: 'string', enum: ['vs-dark', 'vs-light'] },
        readOnly: { type: 'boolean', default: false },
        minimap: { type: 'boolean', default: true },
      },
    },
    eventsSchema: { type: 'object', properties: { onChange: { type: 'object' }, onSave: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 800, height: 600 },
    resizable: true,
    icon: '💻',
    color: '#3B82F6',
    tags: ['code', 'editor', 'monaco'],
  },
  {
    id: 'terminal',
    name: 'Terminal',
    category: 'code',
    description: 'Terminal emulator',
    propsSchema: {
      type: 'object',
      properties: {
        history: { type: 'array' },
        prompt: { type: 'string', default: '$ ' },
        theme: { type: 'string' },
      },
    },
    eventsSchema: { type: 'object', properties: { onCommand: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 700, height: 400 },
    resizable: true,
    icon: '⬛',
    color: '#1F2937',
    tags: ['terminal', 'console', 'shell'],
  },
  {
    id: 'diff-viewer',
    name: 'DiffViewer',
    category: 'code',
    description: 'Code diff viewer',
    propsSchema: {
      type: 'object',
      properties: {
        original: { type: 'string' },
        modified: { type: 'string' },
        language: { type: 'string' },
        inline: { type: 'boolean', default: false },
      },
      required: ['original', 'modified'],
    },
    eventsSchema: { type: 'object', properties: { onAccept: { type: 'object' }, onReject: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 900, height: 600 },
    resizable: true,
    icon: '📑',
    color: '#F59E0B',
    tags: ['diff', 'compare', 'git'],
  },
  {
    id: 'api-tester',
    name: 'APITester',
    category: 'code',
    description: 'API request tester (like Postman)',
    propsSchema: {
      type: 'object',
      properties: {
        method: { type: 'string', enum: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'] },
        url: { type: 'string' },
        headers: { type: 'object' },
        body: { type: 'string' },
        response: { type: 'object' },
      },
    },
    eventsSchema: { type: 'object', properties: { onSend: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 800, height: 600 },
    resizable: true,
    icon: '🔌',
    color: '#10B981',
    tags: ['api', 'rest', 'postman'],
  },
  {
    id: 'regex-tester',
    name: 'RegexTester',
    category: 'code',
    description: 'Regular expression tester',
    propsSchema: {
      type: 'object',
      properties: {
        pattern: { type: 'string' },
        flags: { type: 'string' },
        testString: { type: 'string' },
        matches: { type: 'array' },
      },
    },
    eventsSchema: { type: 'object', properties: { onPatternChange: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 600, height: 400 },
    resizable: true,
    icon: '🔍',
    color: '#EC4899',
    tags: ['regex', 'pattern', 'test'],
  },
  {
    id: 'json-formatter',
    name: 'JSONFormatter',
    category: 'code',
    description: 'JSON formatter and validator',
    propsSchema: {
      type: 'object',
      properties: {
        input: { type: 'string' },
        formatted: { type: 'string' },
        valid: { type: 'boolean' },
        error: { type: 'string' },
      },
    },
    eventsSchema: { type: 'object', properties: { onFormat: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 600, height: 500 },
    resizable: true,
    icon: '{ }',
    color: '#8B5CF6',
    tags: ['json', 'format', 'validate'],
  },

  // ---------------------------------------------------------------------------
  // AI COMPONENTS (4)
  // ---------------------------------------------------------------------------
  {
    id: 'ai-chat',
    name: 'AIChat',
    category: 'ai',
    description: 'Embedded AI chat overlay',
    propsSchema: {
      type: 'object',
      properties: {
        messages: { type: 'array' },
        placeholder: { type: 'string' },
        showSuggestions: { type: 'boolean', default: true },
        contextAware: { type: 'boolean', default: true },
      },
    },
    eventsSchema: { type: 'object', properties: { onSend: { type: 'object' }, onSuggestionClick: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 400, height: 600 },
    resizable: true,
    icon: '🤖',
    color: '#3B82F6',
    tags: ['ai', 'chat', 'assistant'],
  },
  {
    id: 'insight-card',
    name: 'InsightCard',
    category: 'ai',
    description: 'AI-generated insight card',
    propsSchema: {
      type: 'object',
      properties: {
        title: { type: 'string' },
        insight: { type: 'string' },
        confidence: { type: 'number' },
        source: { type: 'string' },
        actions: { type: 'array' },
      },
      required: ['title', 'insight'],
    },
    eventsSchema: { type: 'object', properties: { onActionClick: { type: 'object' }, onDismiss: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 350, height: 200 },
    resizable: false,
    icon: '💡',
    color: '#F59E0B',
    tags: ['insight', 'ai', 'recommendation'],
  },
  {
    id: 'suggestion-panel',
    name: 'SuggestionPanel',
    category: 'ai',
    description: 'AI suggestion panel',
    propsSchema: {
      type: 'object',
      properties: {
        suggestions: { type: 'array' },
        title: { type: 'string' },
        showConfidence: { type: 'boolean', default: true },
      },
    },
    eventsSchema: { type: 'object', properties: { onSuggestionAccept: { type: 'object' }, onSuggestionReject: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 350, height: 400 },
    resizable: true,
    icon: '✨',
    color: '#8B5CF6',
    tags: ['suggestions', 'ai', 'recommendations'],
  },
  {
    id: 'context-inspector',
    name: 'ContextInspector',
    category: 'ai',
    description: 'AI context debugger',
    propsSchema: {
      type: 'object',
      properties: {
        context: { type: 'object' },
        bindings: { type: 'array' },
        showRaw: { type: 'boolean', default: false },
      },
    },
    eventsSchema: { type: 'object', properties: { onContextEdit: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 500, height: 400 },
    resizable: true,
    icon: '🔬',
    color: '#6366F1',
    tags: ['context', 'debug', 'inspector'],
  },

  // ---------------------------------------------------------------------------
  // INPUT COMPONENTS (4)
  // ---------------------------------------------------------------------------
  {
    id: 'form-builder',
    name: 'FormBuilder',
    category: 'input',
    description: 'Dynamic form builder',
    propsSchema: {
      type: 'object',
      properties: {
        fields: { type: 'array' },
        values: { type: 'object' },
        layout: { type: 'string', enum: ['vertical', 'horizontal', 'grid'] },
        submitLabel: { type: 'string', default: 'Submit' },
      },
      required: ['fields'],
    },
    eventsSchema: { type: 'object', properties: { onSubmit: { type: 'object' }, onChange: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 500, height: 600 },
    resizable: true,
    icon: '📝',
    color: '#10B981',
    tags: ['form', 'input', 'fields'],
  },
  {
    id: 'slider-panel',
    name: 'SliderPanel',
    category: 'input',
    description: 'Multiple sliders for parameters',
    propsSchema: {
      type: 'object',
      properties: {
        sliders: { type: 'array' },
        layout: { type: 'string', enum: ['vertical', 'horizontal'] },
      },
      required: ['sliders'],
    },
    eventsSchema: { type: 'object', properties: { onSliderChange: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 400, height: 300 },
    resizable: true,
    icon: '🎚️',
    color: '#8B5CF6',
    tags: ['slider', 'range', 'parameter'],
  },
  {
    id: 'date-range-picker',
    name: 'DateRangePicker',
    category: 'input',
    description: 'Date range selector',
    propsSchema: {
      type: 'object',
      properties: {
        startDate: { type: 'string' },
        endDate: { type: 'string' },
        presets: { type: 'array' },
        minDate: { type: 'string' },
        maxDate: { type: 'string' },
      },
    },
    eventsSchema: { type: 'object', properties: { onRangeChange: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 350, height: 400 },
    resizable: false,
    icon: '📅',
    color: '#EC4899',
    tags: ['date', 'range', 'picker'],
  },
  {
    id: 'search-box',
    name: 'SearchBox',
    category: 'input',
    description: 'Search with suggestions',
    propsSchema: {
      type: 'object',
      properties: {
        placeholder: { type: 'string' },
        suggestions: { type: 'array' },
        value: { type: 'string' },
        debounceMs: { type: 'number', default: 300 },
      },
    },
    eventsSchema: { type: 'object', properties: { onSearch: { type: 'object' }, onSuggestionSelect: { type: 'object' } } },
    supportsInteraction: true,
    supportsDataBinding: true,
    supportsAIContext: true,
    defaultSize: { width: 400, height: 60 },
    resizable: false,
    icon: '🔍',
    color: '#6366F1',
    tags: ['search', 'input', 'autocomplete'],
  },
];

// ============================================================================
// Registry Builder
// ============================================================================

function buildCategoryInfo(): CategoryInfo[] {
  const categories: ComponentCategory[] = ['data', 'visualization', 'productivity', 'finance', 'code', 'ai', 'input', 'layout', 'media', 'custom'];
  
  const categoryMeta: Record<ComponentCategory, { name: string; description: string; icon: string }> = {
    data: { name: 'Data', description: 'Data grids, tables, and viewers', icon: '📊' },
    visualization: { name: 'Visualization', description: 'Charts, graphs, and maps', icon: '📈' },
    productivity: { name: 'Productivity', description: 'Task management and planning', icon: '📋' },
    finance: { name: 'Finance', description: 'Invoices, budgets, and calculators', icon: '💰' },
    code: { name: 'Code', description: 'Editors, terminals, and dev tools', icon: '💻' },
    ai: { name: 'AI', description: 'AI assistants and insights', icon: '🤖' },
    input: { name: 'Input', description: 'Forms and user input', icon: '📝' },
    layout: { name: 'Layout', description: 'Layout containers', icon: '📐' },
    media: { name: 'Media', description: 'Images, video, and audio', icon: '🎬' },
    custom: { name: 'Custom', description: 'User-defined components', icon: '🔧' },
  };

  return categories.map(cat => ({
    id: cat,
    ...categoryMeta[cat],
    componentCount: COMPONENTS.filter(c => c.category === cat).length,
  }));
}

function buildRegistry(): ComponentRegistry {
  const byId: Record<string, LiquidComponent> = {};
  const byCategory: Record<ComponentCategory, LiquidComponent[]> = {
    data: [], visualization: [], productivity: [], finance: [],
    code: [], ai: [], input: [], layout: [], media: [], custom: [],
  };

  for (const comp of COMPONENTS) {
    byId[comp.id] = comp;
    byCategory[comp.category].push(comp);
  }

  return {
    version: '1.0.0',
    components: COMPONENTS,
    categories: buildCategoryInfo(),
    byId,
    byCategory,
  };
}

// ============================================================================
// Exports
// ============================================================================

export const COMPONENT_REGISTRY: ComponentRegistry = buildRegistry();

export function getComponent(id: string): LiquidComponent | undefined {
  return COMPONENT_REGISTRY.byId[id];
}

export function getComponentsByCategory(category: ComponentCategory): LiquidComponent[] {
  return COMPONENT_REGISTRY.byCategory[category] || [];
}

export function searchComponents(query: string): LiquidComponent[] {
  const q = query.toLowerCase();
  return COMPONENT_REGISTRY.components.filter(c =>
    c.name.toLowerCase().includes(q) ||
    c.description.toLowerCase().includes(q) ||
    c.tags.some(t => t.includes(q))
  );
}

export function suggestComponents(intent: string): LiquidComponent[] {
  const intentKeywords: Record<string, string[]> = {
    data_analysis: ['data-grid', 'pivot-table', 'line-chart', 'bar-chart'],
    tracking: ['invoice', 'expense-table', 'kanban', 'todo-list'],
    visualization: ['line-chart', 'bar-chart', 'pie-chart', 'geo-map'],
    planning: ['kanban', 'gantt', 'calendar', 'timeline'],
    calculation: ['calculator', 'data-grid', 'pivot-table'],
    design: ['whiteboard', 'mindmap', 'form-builder'],
    coding: ['code-editor', 'terminal', 'api-tester', 'diff-viewer'],
    writing: ['notes', 'mindmap', 'whiteboard'],
  };

  const suggested = intentKeywords[intent] || [];
  return suggested.map(id => COMPONENT_REGISTRY.byId[id]).filter(Boolean);
}
